### ISSUE TITLE
Incompatibility with JBoss/Wildfly logging manager

### ISSUE THREAD

**Issue by UnasZole** [jvm-profiling-tools/async-profiler#609] opened 2022-06-14 15:39 UTC
Hi,

Following your delivery of the HTTP API I had requested in #512 , I decided to try it out with one of my company's JBoss-based applications.

The good news is that once I got it to start, it works great, and exactly as expected.
Thanks a lot again for that delivery ! :-) 

The less good news is that it's tricky to get it to start when deploying the agent with "agentpath" at startup, because of a long standing issue in JBoss.
Basically, the agent writes some logs using the default java logging manager, before JBoss finished starting and registering its own, leading to a crash of JBoss. (WFLYCTL0079: Failed initializing module org.jboss.as.logging)
The issue is well known (see https://stackoverflow.com/a/22168660 , https://issues.redhat.com/browse/THORN-204 ), and is clearly on Jboss side - not really a bug on your side at all.

On my side it was fixed by adding the following startup options :

> -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Xbootclasspath/p:/opt/jboss/container/wildfly/s2i/galleon/galleon-m2-repository/org/wildfly/common/wildfly-common/1.5.4.Final-redhat-00001/wildfly-common-1.5.4.Final-redhat-00001.jar -Xbootclasspath/p:/opt/jboss/container/wildfly/s2i/galleon/galleon-m2-repository/org/jboss/logmanager/jboss-logmanager/2.1.18.Final-redhat-00001/jboss-logmanager-2.1.18.Final-redhat-00001.jar -Xbootclasspath/p:/opt/jboss/container/wildfly/s2i/galleon/galleon-m2-repository/org/jboss/logmanager/log4j2-jboss-logmanager/1.0.0.Final-redhat-00001/log4j2-jboss-logmanager-1.0.0.Final-redhat-00001.jar -agentpath:/opt/eap/standalone/lib/ext/asyncprofileragt/async-profiler-2.8.1-linux-x64/build/libasyncProfiler.so='server=8374'

And the following environment variable : JBOSS_MODULES_SYSTEM_PKGS="org.jboss.byteman,org.jboss.logmanager"

That being said, while it's clearly not a bug on your side, I've been using a number of other agents that didn't have the issue (like jacoco, elasticapm, ocelot...).
I'm not sure what strategy they use for logging that doesn't cause the conflict, but it'd be interesting to look into it, to maximize compatibility of your agent :-)

**Comment by apangin** [comment] 2022-06-30 22:33
Thank you for the report. Any suggestions on how to deal with the problem?
async-profiler does not even use Java logging directly.

**Comment by apangin** [comment] 2022-09-16 17:03
Let me close the issue, since I don't see what async-profiler can do differently in this regard.
As you noticed, the problem is not even in the profiler, and also a workaround exists.
If you have an idea how async-profiler can avoid the issue, let me know, and I'll get back to this.

**Closed by apangin** 2022-09-16 17:03 UTC
Labels: external

**Comment by UnasZole** [comment] 2022-12-01 10:46
Hi again,

For what it's worth, we've recently tested on more recent versions (OpenJDK 11.0.16 and JBoss 7.4.7), and the issue completely disappeared, we are able to start asyncprofiler on JBoss without the workaround anymore.

So the issue was probably fixed on JBoss side - nothing more to do here :-)
