### ISSUE TITLE
Could not start attach mechanism: No such file or directory

### ISSUE THREAD

**Issue by mahesh-tier1app** [jvm-profiling-tools/async-profiler#464] opened 2021-09-21 11:21 UTC
I am running a java application inside the container and jattach on the host. The java process id on the host is ```20557```. When I execute the jattach to capture threaddump and heapdump from the host. I get the below errors - 

Thread dump - ```Could not start attach mechanism: No such file or directory```

Heap Dump - 

`Resp: capture heap dump failed: exit status 1: exit status 1 because 20557:
  com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/20557/root/tmp/.java_pid20557: target process 20557 doesn't respond within 10500ms or HotSpot VM not loaded
          at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:100)
          at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
          at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
          at jdk.jcmd/sun.tools.jcmd.JCmd.executeCommandForPid(JCmd.java:114)
          at jdk.jcmd/sun.tools.jcmd.JCmd.main(JCmd.java:98)`

I have seen the troubleshooting section in this [link](https://github.com/jvm-profiling-tools/async-profiler#troubleshooting)

1. Attach socket file ```.java_pidNNN``` is not present in ```/tmp``` directory on the host. when I execute ```lsof -p PID | grep java_pid``` it doesn't return any output.
2. I have not started JVM with ```-XX:+DisableAttachMechanism```.
3. Command ```kill -3 PID``` doesn't return anything.

It works if I pass ```-XX:+StartAttachListener``` to JVM but still ```.java_pidNNN``` file is missing in ```/tmp``` directory on the host.

Is there any way to fix this issue without passing ```-XX:+StartAttachListener``` to JVM?

**JDK -** 
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode, sharing)

**OS -** 

CentOS Linux release 7.9.2009 (Core)
3.10.0-1160.42.2.el7.x86_64

**Comment by apangin** [comment] 2021-09-21 12:06
Not related to async-profiler.
Duplicate of https://github.com/apangin/jattach/issues/47

**Closed by apangin** 2021-09-21 12:06 UTC
