### ISSUE TITLE
JVMs crashing after running async profiler

### ISSUE THREAD

**Issue by xpuchly** [jvm-profiling-tools/async-profiler#320] opened 2020-05-14 07:11 UTC
We're running JDK11(.05, .06) and when running async profiler on those, we started to receive this error:  A fatal error has been detected by the Java Runtime Environment:

  Internal Error (codeCache.cpp:626), pid=31780, tid=62010
  guarantee(result == NULL || !result->is_zombie() || result->is_locked_by_vm() || VMError::is_error_reported()) failed: unsafe access to zombie method

Current Thread

Stack: [0x00007f7d41be0000,0x00007f7d41ce1000],  sp=0x00007f7d41cdb500,  free space=1005k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xe2ae23]  VMError::report_and_die(int, char const*, char const*, __va_list_tag*, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long)+0x353
V  [libjvm.so+0xe2ba4f]  VMError::report_and_die(Thread*, void*, char const*, int, char const*, char const*, __va_list_tag*)+0x2f
V  [libjvm.so+0x698346]  report_vm_error(char const*, int, char const*, char const*, ...)+0x106
V  [libjvm.so+0x5f40b2]  CodeCache::find_blob(void*)+0xc2
V  [libjvm.so+0x75cca3]  frame::sender(RegisterMap*) const+0x273
V  [libjvm.so+0x271052]  forte_fill_call_trace_given_top(JavaThread*, ASGCT_CallTrace*, int, frame) [clone .isra.19]+0xbe
V  [libjvm.so+0x758f2e]  AsyncGetCallTrace+0x18e

**Comment by apangin** [comment] 2020-05-14 09:05
What version of the profiler do you use?
Can you send the complete hs_err.log?
(In particular, I'm interested in registers, top of stack, memory map and part of the stack trace related to libasyncProfiler.so).

**Comment by apangin** [comment] 2020-05-27 10:09
@xpuchly Can you please answer the above questions / provide any additional details on reproducing the problem?

**Comment by apangin** [comment] 2020-06-14 21:43
Since there is no more information, I'm closing the issue as not reproducible.

**Closed by apangin** 2020-06-14 21:43 UTC
Labels: need more details
