### ISSUE TITLE
SIGSEGV profiler 2.5, jdk 11.0.11.9.1

### ISSUE THREAD

**Issue by krzysztofslusarski** [jvm-profiling-tools/async-profiler#523] opened 2021-12-16 09:27 UTC
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f9f0f54796c, pid=30189, tid=30300
#
# JRE version: OpenJDK Runtime Environment Corretto-11.0.11.9.1 (11.0.11+9) (build 11.0.11+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.11.9.1 (11.0.11+9-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xbd996c]  Method::checked_resolve_jmethod_id(_jmethodID*)+0x1c
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-11/issues/
#

---------------  S U M M A R Y ------------

....

Host: Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, 2 cores, 11G, CentOS Linux release 7.3.1611 (Core) 
Time: Thu Dec 16 02:05:48 2021 CET elapsed time: 36274.506942 seconds (0d 10h 4m 34s)

---------------  T H R E A D  ---------------

Current thread (0x00007f9f0b3f3800):  JavaThread "cont-prof-1" [_thread_in_vm, id=30300, stack(0x00007f9ea45d9000,0x00007f9ea46da000)]

Stack: [0x00007f9ea45d9000,0x00007f9ea46da000],  sp=0x00007f9ea46d7dc0,  free space=1019k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xbd996c]  Method::checked_resolve_jmethod_id(_jmethodID*)+0x1c
V  [libjvm.so+0x9eada8]  jvmti_GetMethodDeclaringClass+0x1d8
C  [libasyncProfiler.so+0x18317]  Recording::writeStackTraces(Buffer*, Lookup*)+0x2c7
C  [libasyncProfiler.so+0x19770]  Recording::writeCpool(Buffer*)+0xa00
C  [libasyncProfiler.so+0x1b054]  Recording::~Recording()+0x7d4
C  [libasyncProfiler.so+0x10514]  FlightRecorder::stop()+0x94
C  [libasyncProfiler.so+0x39ce6]  Profiler::stop()+0x146
C  [libasyncProfiler.so+0x3d489]  Profiler::runInternal(Arguments&, std::ostream&)+0x369
C  [libasyncProfiler.so+0x227e4]  Java_one_profiler_AsyncProfiler_execute0+0x5b4
J 28916  one.profiler.AsyncProfiler.execute0(Ljava/lang/String;)Ljava/lang/String; (0 bytes) @ 0x00007f9ef9dfcd7f [0x00007f9ef9dfccc0+0x00000000000000bf]
...

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 28916  one.profiler.AsyncProfiler.execute0(Ljava/lang/String;)Ljava/lang/String; (0 bytes) @ 0x00007f9ef9dfcd0c [0x00007f9ef9dfccc0+0x000000000000004c]
...

siginfo: si_signo: 11 (SIGSEGV), si_code: 128 (SI_KERNEL), si_addr: 0x0000000000000000

Register to memory mapping:

RAX=0x0000000000000074 is an unknown value
RBX=0x122c2900b61b00b4 is an unknown value
RCX=0x00007f9ed853b690 points into unknown readable memory: 0x0000000000000000 | 00 00 00 00 00 00 00 00
RDX=0x0000000000000001 is an unknown value
RSP=0x00007f9ea46d7dc0 is pointing into the stack for thread: 0x00007f9f0b3f3800
RBP=0x00007f9ea46d7dd0 is pointing into the stack for thread: 0x00007f9f0b3f3800
RSI=0x00007f9f0b3f3800 is a thread
RDI=0x00007f9f0000001d points into unknown readable memory: b4 00 1b
R8 =0x0000000000000004 is an unknown value
R9 =0x0000000000000058 is an unknown value
R10=0x0000000000000006 is an unknown value
R11=0x0000000000000002 is an unknown value
R12=0x00007f9f0a23f0a0 points into unknown readable memory: 0x00007f9f0fea5f80 | 80 5f ea 0f 9f 7f 00 00
R13=0x00007f9ea46d7eb0 is pointing into the stack for thread: 0x00007f9f0b3f3800
R14=0x00007f9f0000001d points into unknown readable memory: b4 00 1b
R15=0x00007f9ea46d7e00 is pointing into the stack for thread: 0x00007f9f0b3f3800


Registers:
RAX=0x0000000000000074, RBX=0x122c2900b61b00b4, RCX=0x00007f9ed853b690, RDX=0x0000000000000001
RSP=0x00007f9ea46d7dc0, RBP=0x00007f9ea46d7dd0, RSI=0x00007f9f0b3f3800, RDI=0x00007f9f0000001d
R8 =0x0000000000000004, R9 =0x0000000000000058, R10=0x0000000000000006, R11=0x0000000000000002
R12=0x00007f9f0a23f0a0, R13=0x00007f9ea46d7eb0, R14=0x00007f9f0000001d, R15=0x00007f9ea46d7e00
RIP=0x00007f9f0f54796c, EFLAGS=0x0000000000010216, CSGSFS=0x0000000000000033, ERR=0x0000000000000000
  TRAPNO=0x000000000000000d

Top of Stack: (sp=0x00007f9ea46d7dc0)
0x00007f9ea46d7dc0:   00007f9ea46d7f20 00007f9f0b3f3800
0x00007f9ea46d7dd0:   00007f9ea46d7e50 00007f9f0f358da8
0x00007f9ea46d7de0:   00007f9ed853b690 00007f9ea1790fda
0x00007f9ea46d7df0:   00007f9f0b3f3800 00007f9f0b3f3800 

Instructions: (pc=0x00007f9f0f54796c)
0x00007f9f0f54786c:   85 ff 41 8b 4c 24 10 49 89 44 24 08 85 c9 7e 27
0x00007f9f0f54787c:   31 c9 31 d2 eb 0b 66 0f 1f 44 00 00 49 8b 44 24
0x00007f9f0f54788c:   08 48 c7 04 08 37 00 00 00 83 c2 01 48 83 c1 08
0x00007f9f0f54789c:   41 39 54 24 10 7f e5 4d 89 74 24 20 4c 89 63 60
0x00007f9f0f5478ac:   e9 c4 fc ff ff 90 0f 1f 40 00 66 2e 0f 1f 84 00
0x00007f9f0f5478bc:   00 00 00 00 55 48 c7 06 37 00 00 00 48 89 e5 5d
0x00007f9f0f5478cc:   c3 90 66 90 55 48 89 37 48 89 e5 5d c3 90 66 0f
0x00007f9f0f5478dc:   1f 44 00 00 48 8b 07 55 48 89 e5 48 8b 40 08 48
0x00007f9f0f5478ec:   8b 40 08 48 8b 40 18 48 8b 80 98 00 00 00 48 8b
0x00007f9f0f5478fc:   50 60 48 85 d2 0f 94 c0 48 85 ff 0f 94 c1 08 c8
0x00007f9f0f54790c:   75 32 48 83 c2 08 66 0f 1f 44 00 00 48 8b 0a 48
0x00007f9f0f54791c:   39 cf 72 0d 48 63 72 08 48 8d 0c f1 48 39 cf 72
0x00007f9f0f54792c:   1b 48 8b 52 10 48 85 d2 75 e2 5d c3 0f 1f 84 00
0x00007f9f0f54793c:   00 00 00 00 31 c0 5d c3 0f 1f 40 00 b8 01 00 00
0x00007f9f0f54794c:   00 5d c3 90 55 48 89 e5 53 48 83 ec 08 48 85 ff
0x00007f9f0f54795c:   74 3b 48 8b 1f 48 85 db 74 33 48 83 fb 37 74 2d
0x00007f9f0f54796c:   48 8b 03 48 8d 15 da af ad ff 48 8b 40 10 48 39
0x00007f9f0f54797c:   d0 75 11 48 83 c4 08 48 89 d8 5b 5d c3 0f 1f 80
0x00007f9f0f54798c:   00 00 00 00 48 89 df ff d0 84 c0 75 e6 31 db 48
0x00007f9f0f54799c:   83 c4 08 48 89 d8 5b 5d c3 90 66 2e 0f 1f 84 00
0x00007f9f0f5479ac:   00 00 00 00 48 8b 4f 60 55 48 89 e5 48 83 c1 08
0x00007f9f0f5479bc:   74 32 66 90 8b 41 08 85 c0 7e 20 31 d2 31 c0 0f
0x00007f9f0f5479cc:   1f 44 00 00 48 8b 31 83 c0 01 48 c7 04 16 00 00
0x00007f9f0f5479dc:   00 00 48 83 c2 08 39 41 08 7f e9 48 8b 49 10 48
0x00007f9f0f5479ec:   85 c9 75 d0 5d c3 0f 1f 40 00 66 2e 0f 1f 84 00
0x00007f9f0f5479fc:   00 00 00 00 48 8d 05 81 16 94 00 48 39 07 55 48
0x00007f9f0f547a0c:   89 e5 5d 0f 94 c0 c3 90 66 90 66 2e 0f 1f 84 00
0x00007f9f0f547a1c:   00 00 00 00 48 85 ff 74 4b 40 f6 c7 07 75 45 48
0x00007f9f0f547a2c:   8d 05 ae 98 98 00 48 3b 38 73 0c 48 8d 05 aa 98
0x00007f9f0f547a3c:   98 00 48 3b 38 73 45 55 48 89 e5 53 48 89 fb 48
0x00007f9f0f547a4c:   83 ec 08 e8 4c 78 fe ff 84 c0 74 20 48 8d 05 29
0x00007f9f0f547a5c:   16 94 00 48 39 03 0f 94 c0 48 83 c4 08 5b 5d c3 


Stack slot to memory mapping:
stack at sp + 0 slots: 0x00007f9ea46d7f20 is pointing into the stack for thread: 0x00007f9f0b3f3800
stack at sp + 1 slots: 0x00007f9f0b3f3800 is a thread
stack at sp + 2 slots: 0x00007f9ea46d7e50 is pointing into the stack for thread: 0x00007f9f0b3f3800
stack at sp + 3 slots: 0x00007f9f0f358da8: <offset 0x00000000009eada8> in /opt/jdk_11.0.11.9.1_corretto/lib/server/libjvm.so at 0x00007f9f0e96e000
stack at sp + 4 slots: 0x00007f9ed853b690 points into unknown readable memory: 0x0000000000000000 | 00 00 00 00 00 00 00 00
stack at sp + 5 slots: 0x00007f9ea1790fda: <offset 0x0000000000017fda> in /opt/async-profiler/build/libasyncProfiler.so at 0x00007f9ea1779000
stack at sp + 6 slots: 0x00007f9f0b3f3800 is a thread
stack at sp + 7 slots: 0x00007f9f0b3f3800 is a thread

---------------  P R O C E S S  ---------------

Threads class SMR info:
_java_thread_list=0x00007f9eb07c3230, length=89, elements={
0x00007f9f0827c000, 0x00007f9f08280000, 0x00007f9f08295000, 0x00007f9f08297000,
0x00007f9f08299000, 0x00007f9f0829b800, 0x00007f9f0829d000, 0x00007f9f08330000,
0x00007f9f084ed800, 0x00007f9f084f4800, 0x00007f9f084c5000, 0x00007f9f090ff800,
0x00007f9f0910a800, 0x00007f9f08b32800, 0x00007f9f09d21800, 0x00007f9f09d26800,
0x00007f9f09d2e800, 0x00007f9f09c65000, 0x00007f9f09d0e000, 0x00007f9f09ddc000,
0x00007f9f09dde000, 0x00007f9f09de0000, 0x00007f9f09de2000, 0x00007f9f09cc9000,
0x00007f9f09536000, 0x00007f9ed800b800, 0x00007f9f0a3ae000, 0x00007f9f0a3de800,
0x00007f9f0a3e3800, 0x00007f9f0a3e7800, 0x00007f9f0a3e9800, 0x00007f9f0a3eb800,
0x00007f9f0a3ee000, 0x00007f9f0a3f0000, 0x00007f9f0a3f2000, 0x00007f9f0a3f4000,
0x00007f9f0a421000, 0x00007f9f0a426000, 0x00007f9f0a42b000, 0x00007f9f0a42f800,
0x00007f9f0a434800, 0x00007f9f0a439800, 0x00007f9f0a448800, 0x00007f9f0a44c000,
0x00007f9f09d79800, 0x00007f9f08d92000, 0x00007f9f0a15f000, 0x00007f9f09a44000,
0x00007f9f095aa800, 0x00007f9edc009800, 0x00007f9ee000d800, 0x00007f9ee4025800,
0x00007f9f0a0da000, 0x00007f9f0a3d1000, 0x00007f9f095e9000, 0x00007f9f0b3f3800,
0x00007f9f0b3f4000, 0x00007f9f0ab30000, 0x00007f9f09b9f800, 0x00007f9f0aa8a000,
0x00007f9f0a540800, 0x00007f9f0a32a000, 0x00007f9f0a577800, 0x00007f9f08d74000,
0x00007f9f0a548000, 0x00007f9f09a38000, 0x00007f9f08c3c800, 0x00007f9f0a398800,
0x00007f9f08d53000, 0x00007f9f0a39d800, 0x00007f9f0a57b800, 0x00007f9edc050000,
0x00007f9f0971d800, 0x00007f9f08028800, 0x00007f9edc0dc800, 0x00007f9eb4170000,
0x00007f9ea8031800, 0x00007f9ea8035800, 0x00007f9ebd7a4800, 0x00007f9eb45f2000,
0x00007f9ee0016800, 0x00007f9edc1a0800, 0x00007f9ee4096800, 0x00007f9ee0019000,
0x00007f9ee40bd800, 0x00007f9ecc024000, 0x00007f9ea800a000, 0x00007f9ea8022000,
0x00007f9ea8010000
}
...
```

If you need more data, let me know, i will obfuscate the hs_err.

```shell
# ./profiler.sh -v
Async-profiler 2.5 built on Oct  1 2021
Copyright 2016-2021 Andrei Pangin
```

**Comment by krzysztofslusarski** [comment] 2021-12-16 09:36
Another one:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff63dd02181, pid=22535, tid=24002
#
# JRE version: OpenJDK Runtime Environment Corretto-11.0.11.9.1 (11.0.11+9) (build 11.0.11+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.11.9.1 (11.0.11+9-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libasyncProfiler.so+0x18181]  Recording::writeStackTraces(Buffer*, Lookup*)+0x131
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-11/issues/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

...

Host: Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, 2 cores, 11G, CentOS Linux release 7.3.1611 (Core) 
Time: Fri Dec 10 18:23:41 2021 CET elapsed time: 7531.800296 seconds (0d 2h 5m 31s)

---------------  T H R E A D  ---------------

Current thread (0x00007ff6b31cb620):  JavaThread "cont-prof-1" [_thread_in_native, id=24002, stack(0x00007ff63ccca000,0x00007ff63cdcb000)]

Stack: [0x00007ff63ccca000,0x00007ff63cdcb000],  sp=0x00007ff63cdc8e70,  free space=1019k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libasyncProfiler.so+0x18181]  Recording::writeStackTraces(Buffer*, Lookup*)+0x131
C  [libasyncProfiler.so+0x19770]  Recording::writeCpool(Buffer*)+0xa00
C  [libasyncProfiler.so+0x1b054]  Recording::~Recording()+0x7d4
C  [libasyncProfiler.so+0x10514]  FlightRecorder::stop()+0x94
C  [libasyncProfiler.so+0x39ce6]  Profiler::stop()+0x146
C  [libasyncProfiler.so+0x3d489]  Profiler::runInternal(Arguments&, std::ostream&)+0x369
C  [libasyncProfiler.so+0x227e4]  Java_one_profiler_AsyncProfiler_execute0+0x5b4
j  one.profiler.AsyncProfiler.execute0(Ljava/lang/String;)Ljava/lang/String;+0
j  one.profiler.AsyncProfiler.execute(Ljava/lang/String;)Ljava/lang/String;+2
...

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  one.profiler.AsyncProfiler.execute0(Ljava/lang/String;)Ljava/lang/String;+0
j  one.profiler.AsyncProfiler.execute(Ljava/lang/String;)Ljava/lang/String;+2
...

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000000

Register to memory mapping:

RAX=0x00000000000023f0 is an unknown value
RBX=0x00005639c07c6310 points into unknown readable memory: 0xc592650f000023f1 | f1 23 00 00 0f 65 92 c5
RCX=0x0 is NULL
RDX=0x00000000000023f1 is an unknown value
RSP=0x00007ff63cdc8e70 is pointing into the stack for thread: 0x00007ff6b31cb620
RBP=0x00007ff63cdc8fa0 is pointing into the stack for thread: 0x00007ff6b31cb620
RSI=0x00000000000023eb is an unknown value
RDI=0x00005639c09165f0 points into unknown readable memory: 0x00007ff600000001 | 01 00 00 00 f6 7f 00 00
R8 =0x000000000000000b is an unknown value
R9 =0x0000000000000003 is an unknown value
R10=0x0000000000000030 is an unknown value
R11=0x0000000000000002 is an unknown value
R12=0x00000000000023ef is an unknown value
R13=0x00007ff6b31c7678 points into unknown readable memory: 0x00007ff68d0b2868 | 68 28 0b 8d f6 7f 00 00
R14=0x00007ff6b072a7c0 points into unknown readable memory: 0x00007ff6b8093f80 | 80 3f 09 b8 f6 7f 00 00
R15=0x00007ff63cdc9060 is pointing into the stack for thread: 0x00007ff6b31cb620


Registers:
RAX=0x00000000000023f0, RBX=0x00005639c07c6310, RCX=0x0000000000000000, RDX=0x00000000000023f1
RSP=0x00007ff63cdc8e70, RBP=0x00007ff63cdc8fa0, RSI=0x00000000000023eb, RDI=0x00005639c09165f0
R8 =0x000000000000000b, R9 =0x0000000000000003, R10=0x0000000000000030, R11=0x0000000000000002
R12=0x00000000000023ef, R13=0x00007ff6b31c7678, R14=0x00007ff6b072a7c0, R15=0x00007ff63cdc9060
RIP=0x00007ff63dd02181, EFLAGS=0x0000000000010293, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007ff63cdc8e70)
0x00007ff63cdc8e70:   00007ff63cdc8e9f 00005639c0917cc0
0x00007ff63cdc8e80:   00005639c0916630 00005639c07c6310
0x00007ff63cdc8e90:   00007ff63cdc9080 0000000000000000
0x00007ff63cdc8ea0:   00007ff63cfcddc0 00000007014d7760 

Instructions: (pc=0x00007ff63dd02181)
0x00007ff63dd02081:   ff ff 48 89 45 80 48 8b 05 32 a9 23 00 48 89 bd
0x00007ff63dd02091:   e8 fe ff ff c7 85 68 ff ff ff 00 00 00 00 48 c7
0x00007ff63dd020a1:   85 70 ff ff ff 00 00 00 00 48 c7 45 88 00 00 00
0x00007ff63dd020b1:   00 48 8b 38 48 81 c7 10 81 00 00 e8 7f fd fe ff
0x00007ff63dd020c1:   8b 13 48 63 c2 83 c2 01 c6 44 03 04 1a 8b 45 88
0x00007ff63dd020d1:   89 13 83 f8 7f 76 17 89 c1 c1 e8 07 48 63 fa 83
0x00007ff63dd020e1:   c9 80 83 c2 01 83 f8 7f 88 4c 3b 04 77 e9 48 63
0x00007ff63dd020f1:   ca 44 8d 62 01 88 44 0b 04 48 8b 85 78 ff ff ff
0x00007ff63dd02101:   44 89 23 48 89 85 e0 fe ff ff 48 8d 85 60 ff ff
0x00007ff63dd02111:   ff 48 83 c0 08 48 39 85 e0 fe ff ff 0f 84 fc 07
0x00007ff63dd02121:   00 00 48 8b 85 e0 fe ff ff 48 8b 95 e0 fe ff ff
0x00007ff63dd02131:   48 8b 40 28 48 89 85 f8 fe ff ff 8b 42 20 83 f8
0x00007ff63dd02141:   7f 76 1c 0f 1f 40 00 89 c1 c1 e8 07 49 63 d4 83
0x00007ff63dd02151:   c9 80 41 83 c4 01 83 f8 7f 88 4c 13 04 77 e8 49
0x00007ff63dd02161:   63 cc 41 8d 54 24 02 88 44 0b 04 41 8d 44 24 01
0x00007ff63dd02171:   48 8b 8d f8 fe ff ff 89 13 48 98 c6 44 03 04 00
0x00007ff63dd02181:   8b 01 83 f8 7f 76 22 48 89 df 0f 1f 44 00 00 89
0x00007ff63dd02191:   c3 c1 e8 07 48 63 ca 83 cb 80 83 c2 01 83 f8 7f
0x00007ff63dd021a1:   88 5c 0f 04 77 e9 48 89 fb 48 63 ca 44 8d 62 01
0x00007ff63dd021b1:   88 44 0b 04 48 8b 85 f8 fe ff ff 44 89 23 8b 10
0x00007ff63dd021c1:   85 d2 0f 8e 02 07 00 00 48 89 85 00 ff ff ff c7
0x00007ff63dd021d1:   85 0c ff ff ff 00 00 00 00 66 0f 1f 44 00 00 4c
0x00007ff63dd021e1:   63 b5 0c ff ff ff 49 8b 3f 48 8b 47 10 48 8d 57
0x00007ff63dd021f1:   08 49 c1 e6 04 4c 03 b5 f8 fe ff ff 49 89 d4 48
0x00007ff63dd02201:   85 c0 4d 8b 6e 10 75 13 eb 2c 0f 1f 44 00 00 49
0x00007ff63dd02211:   89 c4 48 8b 40 10 48 85 c0 74 0f 4c 3b 68 20 76
0x00007ff63dd02221:   ee 48 8b 40 18 48 85 c0 75 f1 4c 39 e2 74 07 4d
0x00007ff63dd02231:   3b 6c 24 20 73 50 48 8d 55 90 4c 89 e6 4c 89 6d
0x00007ff63dd02241:   90 c6 45 98 00 c7 45 9c 00 00 00 00 c7 45 a0 00
0x00007ff63dd02251:   00 00 00 c7 45 a4 00 00 00 00 c7 45 a8 00 00 00
0x00007ff63dd02261:   00 c7 45 ac 00 00 00 00 c7 45 b0 00 00 00 00 48
0x00007ff63dd02271:   c7 45 b8 00 00 00 00 c7 45 c0 00 00 00 00 e8 1c 


Stack slot to memory mapping:
stack at sp + 0 slots: 0x00007ff63cdc8e9f is pointing into the stack for thread: 0x00007ff6b31cb620
stack at sp + 1 slots: 0x00005639c0917cc0 points into unknown readable memory: 0x00007ff6b806fe28 | 28 fe 06 b8 f6 7f 00 00
stack at sp + 2 slots: 0x00005639c0916630 points into unknown readable memory: 0x00007ff600000001 | 01 00 00 00 f6 7f 00 00
stack at sp + 3 slots: 0x00005639c07c6310 points into unknown readable memory: 0xc592650f000023f1 | f1 23 00 00 0f 65 92 c5
stack at sp + 4 slots: 0x00007ff63cdc9080 is pointing into the stack for thread: 0x00007ff6b31cb620
stack at sp + 5 slots: 0x0 is NULL
stack at sp + 6 slots: 0x00007ff63cfcddc0 points into unknown readable memory: 0x00007ff6b31c7678 | 78 76 1c b3 f6 7f 00 00
stack at sp + 7 slots: 0x00000007014d7760 is an unknown value


---------------  P R O C E S S  ---------------

Threads class SMR info:
_java_thread_list=0x00007ff654043380, length=103, elements={
0x00007ff6b03d6120, 0x00007ff6b03d9c50, 0x00007ff6b03ee530, 0x00007ff6b03efe70,
0x00007ff6b03f1990, 0x00007ff6b03f3410, 0x00007ff6b03f4d60, 0x00007ff6b0487780,
0x00007ff6b06350c0, 0x00007ff6b063ba70, 0x00007ff6b060c770, 0x00007ff6b0a118e0,
0x00007ff6b077b970, 0x00007ff6b078a500, 0x00007ff6b161c900, 0x00007ff6b188b970,
0x00007ff6b1646490, 0x00007ff6b2a630f0, 0x00007ff6b2873660, 0x00007ff6b1d6d870,
0x00007ff6b24bf7f0, 0x00007ff65400c190, 0x00007ff66c003340, 0x00007ff65c000f60,
0x00007ff6b21a6410, 0x00007ff6b298c220, 0x00007ff6b1b02ce0, 0x00007ff6b3253af0,
0x00007ff6b2be13e0, 0x00007ff6b2be1f10, 0x00007ff6b1763380, 0x00007ff6b1763cf0,
0x00007ff6b24a9bf0, 0x00007ff6b21616d0, 0x00007ff6b126d270, 0x00007ff67c0087e0,
0x00007ff6b2dad580, 0x00007ff6b301ea60, 0x00007ff6b3024aa0, 0x00007ff6b302fc40,
0x00007ff6b3035600, 0x00007ff6b3037040, 0x00007ff6b3038a70, 0x00007ff6b303a4f0,
0x00007ff6b303bf80, 0x00007ff6b303da10, 0x00007ff6b30bf0f0, 0x00007ff6b30c3800,
0x00007ff6b30c82c0, 0x00007ff6b30ccdb0, 0x00007ff6b30d1790, 0x00007ff6b30d6270,
0x00007ff6b30ec940, 0x00007ff6b30f9de0, 0x00007ff6b3c04c10, 0x00007ff6b0fef2c0,
0x00007ff6b07e1620, 0x00007ff6b0f781f0, 0x00007ff6b0ef7a50, 0x00007ff6b31cb620,
0x00007ff6b31bc400, 0x00007ff6b3aa5110, 0x00007ff6b0e1b930, 0x00007ff6b399cf20,
0x00007ff6b399d810, 0x00007ff6b06a80b0, 0x00007ff6b2a13d90, 0x00007ff6b1c990d0,
0x00007ff6b2a130c0, 0x00007ff6b21ed760, 0x00007ff6b29786b0, 0x00007ff6b0cb6ea0,
0x00007ff6b21eb650, 0x00007ff6b2eda380, 0x00007ff6b0eb36b0, 0x00007ff6b0028b30,
0x00007ff67400da70, 0x00007ff674013b90, 0x00007ff64c00d690, 0x00007ff674016090,
0x00007ff658ed9160, 0x00007ff64c2b8420, 0x00007ff66c74e880, 0x00007ff674515bf0,
0x00007ff674519390, 0x00007ff67468ec50, 0x00007ff6746901f0, 0x00007ff6746c4f50,
0x00007ff67477fbd0, 0x00007ff6748774e0, 0x00007ff680005ad0, 0x00007ff68000d0e0,
0x00005639c08d8e70, 0x00005639c08d1f00, 0x00007ff6b31ab300, 0x00007ff6b08ad0a0,
0x00005639c0903880, 0x00007ff65c034d80, 0x00005639c0905260, 0x00007ff658f1a240,
0x00007ff65403f250, 0x00007ff658224980, 0x00007ff658225380
}
...
```

**Comment by apangin** [comment] 2021-12-16 23:51
> If you need more data, let me know, i will obfuscate the hs_err.

Yes, please. If you prefer not to share the file here, send it to me privately at < upload at pangin.pro >

I suspect a JVM bug related to concurrent class unloading.
[JDK-8268364](https://bugs.openjdk.java.net/browse/JDK-8268364) and [JDK-8181110](https://bugs.openjdk.java.net/browse/JDK-8181110) look relevant.
If I had a reliable way to reproduce the problem, I would probably make a workaround in async-profiler.

**Comment by krzysztofslusarski** [comment] 2021-12-17 07:14
I sent those files privately.

I didn't mention one thing. This happens with profiler 2.5, with the same JDK and profiler 1.8.x we don't have any issue.

**Comment by apangin** [comment] 2021-12-21 00:19
Thank you for the crash logs. They convince me the issue is in the profiler.
I think I've found the bug that may be related - the fix is already in `master`.
If you need the prebuilt binaries, here is linux-x64 build: https://profiler.tools/builds/async-profiler-2.5.1-race-linux-x64.tar.gz

**Comment by krzysztofslusarski** [comment] 2021-12-21 06:40
Thank you, we will try that oine.

**Comment by apangin** [comment] 2022-01-10 00:40
async-profiler v2.6 has been [released](https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v2.6).
It has a number of reliability improvements, including a fix for this problem.

**Closed by apangin** 2022-01-10 00:40 UTC
