### ISSUE TITLE
 socket file does not exist

### ISSUE THREAD

**Issue by 2317899011** [jvm-profiling-tools/async-profiler#603] opened 2022-06-02 07:25 UTC
My /tmp/.job_ pidnnnn has been deleted. In this case, how can I use the generate tool or restore it job_ pidNNNN.

**Comment by apangin** [comment] 2022-06-02 08:57
What are you trying to do? How this is related to Java profiling?

**Comment by 2317899011** [comment] 2022-06-02 09:27
I tried to execute this command
`sh async-profiler-2.0-linux-x64/profiler.sh -d 10 -o flamegraph  -f /var/lib/hadoop-hdfs/test/2.html 27112      `      
But an error is reported
`Could not start attach mechanism: No such file or directory`
This is .job_ pidnnnn is caused by deletion. Is there any method to solve it

**Comment by apangin** [comment] 2022-06-03 11:11
I have no idea what `.job_pid` is. Perhaps you mean `/tmp/.java_pidNNN` socket?

The problem is described in [Troubleshooting](https://github.com/jvm-profiling-tools/async-profiler#troubleshooting) section:

> Attach socket /tmp/.java_pidNNN has been deleted. It is a common practice to clean /tmp automatically with some scheduled script. Configure the cleanup software to exclude .java_pid* files from deletion.
> How to check: run lsof -p PID | grep java_pid
> If it lists a socket file, but the file does not exist, then this is exactly the described problem.

What is the result of the above lsof command?

**Comment by 2317899011** [comment] 2022-06-06 03:26
Attach socket /tmp/.java_pidNNN has been deleted.Is there any solution?

**Comment by apangin** [comment] 2022-06-06 21:46
Attach socket is automatically recreated since JDK 14.
This has been fixed in [JDK-8225690](https://bugs.openjdk.org/browse/JDK-8225690) and backported to JDK 11.0.3 and JDK 8u332.
In earlier versions of JDK a deleted attach socket cannot be recreated until JVM restarts.

**Comment by 2317899011** [comment] 2022-06-07 01:29
Get it,thanks.

**Closed** 2022-06-07 08:41 UTC
Labels: jvm bug
