### ISSUE TITLE
SIGSEGV - Corretto-11.0.11.9.1 - async-profiler 1.8.3

### ISSUE THREAD

**Issue by krzysztofslusarski** [jvm-profiling-tools/async-profiler#461] opened 2021-09-13 08:28 UTC
Hi, we had a crash of one of our JVMs with async-profiler in continuous mode:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f705579b173, pid=8748, tid=9285
#
# JRE version: OpenJDK Runtime Environment Corretto-11.0.11.9.1 (11.0.11+9) (build 11.0.11+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.11.9.1 (11.0.11+9-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x27f173]  forte_fill_call_trace_given_top(JavaThread*, ASGCT_CallTrace*, int, frame) [clone .isra.20]+0x15f
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-11/issues/
...
---------------  T H R E A D  ---------------

Current thread (0x00007f6fbda6ff20):  JavaThread "http-nio-8080-exec-2" daemon [_thread_in_Java, id=9285, stack(0x00007f6fc81f2000,0x00007f6fc82f3000)]

Stack: [0x00007f6fc81f2000,0x00007f6fc82f3000],  sp=0x00007f6fc82eab40,  free space=994k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x27f173]  forte_fill_call_trace_given_top(JavaThread*, ASGCT_CallTrace*, int, frame) [clone .isra.20]+0x15f
V  [libjvm.so+0x7866ee]  AsyncGetCallTrace+0x18e
C  [libasyncProfiler.so+0x22561]  Profiler::getJavaTraceAsync(void*, ASGCT_CallFrame*, int)+0x561
C  [libasyncProfiler.so+0x22858]  Profiler::recordSample(void*, unsigned long long, int, _jmethodID*, ThreadState)+0x1f8
C  [libpthread.so.0+0xf630]
V  [libjvm.so+0x8c4db9]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x3b9
V  [libjvm.so+0x8c2fad]  JavaCalls::call_virtual(JavaValue*, Handle, Klass*, Symbol*, Symbol*, Handle, Thread*)+0x1fd
V  [libjvm.so+0xe8efc6]  SystemDictionary::load_instance_class(Symbol*, Handle, Thread*)+0x246
V  [libjvm.so+0xe8d7ba]  SystemDictionary::resolve_instance_class_or_null(Symbol*, Handle, Handle, Thread*)+0x93a
V  [libjvm.so+0xe8dbe2]  SystemDictionary::resolve_or_fail(Symbol*, Handle, Handle, bool, Thread*)+0x22
V  [libjvm.so+0x977760]  find_class_from_class_loader(JNIEnv_*, Symbol*, unsigned char, Handle, Handle, unsigned char, Thread*)+0x30
V  [libjvm.so+0x978e87]  JVM_FindClassFromCaller+0x147
C  [libjava.so+0xe6c8]  Java_java_lang_Class_forName0+0x178
J 1613  java.lang.Class.forName0(Ljava/lang/String;ZLjava/lang/ClassLoader;Ljava/lang/Class;)Ljava/lang/Class; java.base@11.0.11 (0 bytes) @ 0x00007f701f8f2f47 [0x00007f701f8f2e40+0x0000000000000107]
J 32888 c2 javax.el.ImportHandler.resolveClassFor(Ljava/lang/String;)Ljava/lang/Class; (52 bytes) @ 0x00007f70217f60fc [0x00007f70217f5b80+0x000000000000057c]
```

Async-profiler 1.8.3.

Does it a JVM bug?

**Comment by apangin** [comment] 2021-09-13 19:52
Hi,
The bug occured in the JVM when async-profiler attempted to recover otherwise unwalkable stack.
I expect the problem to disappear with `safemode=4` option. However, this may result in a large number of `[unknown_Java]` samples. To get to the root cause and to create a proper workaround I'd need more information: this can be the full `hs_err.log` and/or the problem reproducer.

**Comment by krzysztofslusarski** [comment] 2021-09-13 20:06
[hs_err.log](https://github.com/jvm-profiling-tools/async-profiler/files/7157067/hs_err.log)

I had to obfuscate some parts. I marked them with ```<obfuscated>```.

It will be really hard to reproduce. We use async-profiler 1.8.2+ in continuous mode from ~september 2020 (after you have fixed #350) in almost 30 of JVMs at production. That crash happened one time.

**Comment by apangin** [comment] 2021-09-15 17:11
Thank you for the crash report. The problem happened in a transient state when calling a Java method from VM. Thread has already switched to `in_Java` state, but no Java code has been executed yet. I'll try to simulate this situation and stress test it.

**Comment by krzysztofslusarski** [comment] 2021-09-15 18:10
Thank you.

**Comment by apangin** [comment] 2022-05-10 01:30
I was not able to reproduce this exact crash, however, I completely redid the stack recovery in async-profiler 2.8.
It should be more reliable now.
Let me close this issue as outdated. Please open a new one, if you see a problem in 2.8.

**Closed by apangin** 2022-05-10 01:30 UTC
