### ISSUE TITLE
Java Callback API

### ISSUE THREAD

**Issue by PaulBGD** [jvm-profiling-tools/async-profiler#403] opened 2021-03-23 22:01 UTC
There's a lot of use-cases where the Java API is used to just export profiling data, then re-parse that data into Java. It'd be really interesting to see the samples sent back into Java instead of storing them and exporting them later.

**Comment by apangin** [comment] 2021-03-24 21:31
It's unlikely there will be a Java API for receiving each individual event as a fully parsed Java object. This would be too expensive to do in runtime.

What I plan to implement instead is event streaming. This will allow to process events in batches in a compact JFR-like encoding.

Closing as duplicate of #191.

**Closed by apangin** 2021-03-24 21:31 UTC

**Comment by PaulBGD** [comment] 2021-03-25 00:31
I understand it's more expensive, but for some apps I think the tradeoff of performance vs being able to process samples in real-time is worth it.

**Comment by apangin** [comment] 2021-03-25 23:52
It depends on what you mean by "real-time".
There is no way to notify Java code synchronously about async-profiler's events (or async-profiler wouldn't be called "async" :)
But it's possible to "stream" events continuously and process them shortly after they happen. That's what #404 is about.
