### ISSUE TITLE
JFR + WALL failed to display

### ISSUE THREAD

**Issue by nathanqw** [jvm-profiling-tools/async-profiler#227] opened 2019-07-22 17:14 UTC
I'm using the latest release, for profiling a Spark job, passed the profiler as a Java agent.  

It worked fine and generated a valid jfr file when using the "cpu" option,
  "-agentpath:/shared/libasyncProfiler.so=start,jfr,file=/path/output-cpu.jfr,event=cpu"
But, it failed to load the jfr file with jmc, when switched to "wall", 
  "-agentpath:/shared/libasyncProfiler.so=start,jfr,file=/path/output-wall.jfr,event=wall"
Everything seemed okay, but only that the output file couldn't be loaded into jmc, showing an EOFException.

**Comment by apangin** [comment] 2019-07-23 10:50
What JMC version do you use?

I could not reproduce the problem myself. Is it possible for you to send me the bad jfr file?
Or are there steps I can do to reliably reproduce the bug?

**Comment by nathanqw** [comment] 2019-07-23 17:48
Thanks for the quick response, Andrei!

My Spark was running on Linux (SUSE) with OpenJDK 1.8.0_131 installed.  I scp-ed the .jfr file to my Windows laptop, which had Oracle's Java 1.8.0_162,  and used the jmc there to view the file.  The jfr files are 3~4MB big, I don't know how to send one to you.

As said, "cpu" option worked fine with jfr, and both "cpu" and "wall" worked with svg.

The final cmdline shell script (partial),

javaagent="\"-agentpath:/shared/libasyncProfiler.so=start,title=Sample-wall,jfr,file=/mounted/sample-wall.jfr,event=wall\""

spark-submit --conf "spark.executor.extraJavaOptions=${javaagent}" --master ${spark_master} --class ${class} ${resources} --deploy-mode client ${jar} ${args} appname genSample

Thank you very much!

**Comment by apangin** [comment] 2019-07-24 12:50
Please email the files to:
upload482 @ and.su

**Comment by nathanqw** [comment] 2019-07-25 17:11
Sent one file yesterday.

**Comment by apangin** [comment] 2019-07-25 17:34
Thanks, I received the file.
The recording is mostly valid, except that a couple of metadata offsets got broken. Even though I can recover the recording completely, I don't see how this bug could happen.

Does this problem always happen in your case?
I can probably prepare a fix, but I won't be able to verify it myself, as the problem never occur in my environment.

**Comment by nathanqw** [comment] 2019-07-25 19:43
Yes, only for jfr + wall, tried 4 times, all had the same problem.  Thanks!

**Comment by apangin** [comment] 2019-07-25 22:31
I committed the change that *may* fix the problem. Please, build a version from [jfr-fix](https://github.com/jvm-profiling-tools/async-profiler/tree/jfr-fix) branch, or try [the attached binary](https://github.com/jvm-profiling-tools/async-profiler/files/3433478/async-profiler-1.5-linux-x64.tar.gz).

If it does not help, please send me a new broken file.

**Comment by apangin** [comment] 2019-07-28 00:24
The same problem remains, unfortunately.
Do you run any profiler command before the application terminates? It looks as if the file is written concurrently.

**Comment by apangin** [comment] 2019-07-28 00:30
I added some debug info that is printed in stderr of the JVM process when dumping JFR file.
This looks like
```
JFR-PROF: flushed 35220/35220 bytes of buffer 0x7f0268c60014 from thread 566, file_pos = 35236
```
If you don't mind debugging this issue, please run the attached version - [async-profiler-1.5-linux-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/files/3438735/async-profiler-1.5-linux-x64.tar.gz) - and send me the result file and the debug info (all lines started with JFR-PROF).

**Comment by nathanqw** [comment] 2019-08-01 23:06
Finally got some free time to test this again.  Somehow, this latest version worked without a problem.  For the concurrent writing, that might be caused by multiple Spark tasks writing to the same file on the same worker node.  Will send you the result file later.  Thank you very much for all your help!

**Comment by apangin** [comment] 2019-08-11 14:24
Yes, concurrent writing to the same file may have caused the problem.
Anyway, I've committed the latest changes to the master, so I'm closing the issue for now.

**Closed by apangin** 2019-08-11 14:24 UTC
