### ISSUE TITLE
Attaching async-profiler as an agent breaks java.lang.management.ManagementFactory

### ISSUE THREAD

**Issue by jtjeferreira** [jvm-profiling-tools/async-profiler#647] opened 2022-09-15 13:51 UTC
I was trying to profile a [play](https://github.com/playframework/playframework) application using the [Java agent approach](https://github.com/jvm-profiling-tools/async-profiler/wiki/Embedded-profiling-as-Java-Agent), but got this weird error:

```
Profiling started
Oops, cannot start the server.
java.lang.UnsatisfiedLinkError: no management in system library path: /opt/homebrew/Cellar/openjdk@17/17.0.4.1/libexec/openjdk.jdk/Contents/Home/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.management/java.lang.management.ManagementFactory.lambda$static$8(ManagementFactory.java:1016)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.management/java.lang.management.ManagementFactory.<clinit>(ManagementFactory.java:1015)
	at play.core.server.RealServerProcess.pid(ServerProcess.scala:50)
	at play.core.server.ProdServerStart$.createPidFile(ProdServerStart.scala:145)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:45)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:29)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

The problematic code is in the `java.lang.management.ManagementFactory` static initialiser
```java
static {
        AccessController.doPrivileged((PrivilegedAction<Void>) () -> {
            System.loadLibrary("management");
            return null;
        });
    }
```

If I launch the application with the async-profiler agent it works. Also if I disable all the code that makes use of `java.lang.management.ManagementFactory` the agent works correctly

My environment:
Mac M1 arm64
```
java -version
openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment Homebrew (build 17.0.4.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.4.1+0, mixed mode, sharing)
```

Let me know if more details are needed or even a small reproducer...

**Comment by apangin** [comment] 2022-09-16 16:15
Yes, a reproducer would be helpful: a `.jar` or a `.class` file with the exact run command.
Thanks.

**Comment by jtjeferreira** [comment] 2022-09-16 16:36
> Yes, a reproducer would be helpful: a `.jar` or a `.class` file with the exact run command. Thanks.

Ok, I will work on it. I am wondering if this is related to Mac M1 arm64, as I recently moved from Linux to Mac and I am still figuring things out.

**Comment by apangin** [comment] 2022-09-16 16:47
No, mac should not be an issue. I just tested a Java app that uses `ManagementFactory` on JDK 17.0.4.1 on my M1 mac with async-profiler and everything worked fine. So more details will be highly appreciated. Btw, which version of async-profiler did you use?

**Comment by jtjeferreira** [comment] 2022-09-16 16:52
> which version of async-profiler did you use?

2.8.3

**Comment by jtjeferreira** [comment] 2022-09-16 17:22
Reproduction steps:
```
$ git clone git@github.com:playframework/play-samples.git
$ cd play-samples/
$ cd play-scala-hello-world-tutorial/
$ sbt stage
```
the above will generate an app ready to run in the folder `./target/universal/stage/` which contains a launcher script in `./target/universal/stage/bin/play-scala-hello-world-tutorial`

Running without agent is okay
```
$ ./target/universal/stage/bin/play-scala-hello-world-tutorial -Dplay.http.secret.key='QCY?tAnfk?aZ?iwrNwnxIlR6CTf:G3gf:90Latabg@5241AB`R5W:1uDFN];Ik@n'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/Users/joao/git/play-samples/play-scala-hello-world-tutorial/target/universal/stage/lib/com.google.inject.guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] play.api.Play - Application started (Prod) (no global state)
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
^C
[info] p.a.i.l.c.CoordinatedShutdownSupport - Starting synchronous coordinated shutdown with ServerStoppedReason reason and 2147508000 milliseconds timeout
[info] p.c.s.AkkaHttpServer - Stopping Akka HTTP server...
[info] p.c.s.AkkaHttpServer - Terminating server binding for /0:0:0:0:0:0:0:0:9000
[info] p.c.s.AkkaHttpServer - Running provided shutdown stop hooks
```

Running with `-J-agentlib:asyncProfiler=start,event=cpu,file=profile.html` 
```
./target/universal/stage/bin/play-scala-hello-world-tutorial -Dplay.http.secret.key='QCY?tAnfk?aZ?iwrNwnxIlR6CTf:G3gf:90Latabg@5241AB`R5W:1uDFN];Ik@n'  -J-agentlib:asyncProfiler=start,event=cpu,file=profile.html
Error occurred during initialization of VM
Could not find agent library asyncProfiler on the library path, with error: dlopen(libasyncProfiler.dylib, 0x0001): tried: '/opt/homebrew/Cellar/openjdk@11/11.0.16.1/libexec/openjdk.jdk/Contents/Home/lib/server/./libasyncProfiler.dylib' (no such file), '/opt/homebrew/Cellar/openjdk@11/11.0.16.1/libexec/openjdk.jdk/Contents/Home/lib/server/../libasyncProfiler.dylib' (no such file), '/opt/homebrew/Cellar/openjdk@11/11.0.16.1/libexec/openjdk.jdk/Contents/Home/bin/../lib/jli/libasyncProfiler.dylib' (no such file), 'libasyncProfiler.dylib' (no such file), '/usr/local/lib/libasyncProfiler.dylib' (no such file), '/usr/lib/libasyncProfiler.dylib' (no such file), '/Users/joao/git/play-samples/play-scala-hello-world-tutorial/libasyncProfiler.dylib' (no such file)
``` 

The above error is expected and I fix it by copying the `libasyncProfiler.dylib` to the current dir `cp ~/async-profiler-2.8.3-macos/build/libasyncProfiler.so libasyncProfiler.dylib` (because setting LD_LIBRARY_PATH does not work https://stackoverflow.com/a/60128194 🤷 )

```
$ /target/universal/stage/bin/play-scala-hello-world-tutorial -Dplay.http.secret.key='QCY?tAnfk?aZ?iwrNwnxIlR6CTf:G3gf:90Latabg@5241AB`R5W:1uDFN];Ik@n'  -J-agentlib:asyncProfiler=start,event=cpu,file=profile.html
Profiling started
Error: LinkageError occurred while loading main class play.core.server.ProdServerStart
	java.lang.UnsatisfiedLinkError: no nio in java.library.path: [/Users/joao/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
```

Which is different from initial reported, but still related? I now wonder if this is related to async-profiler at all or my system is not properly configured (I am using homebrew and jenv)
```
$ java -version
openjdk version "11.0.16.1" 2022-08-12
OpenJDK Runtime Environment Homebrew (build 11.0.16.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.16.1+0, mixed mode)
```

**Comment by apangin** [comment] 2022-09-16 18:25
OK, I was able to reproduce the issue.
The problem is in Homebrew JDK.
All other JDK builds I tried (Oracle, Liberica, Azul Zulu) seem to work fine. I'll check later what's wrong with Homebrew builds. Meanwhile try installing JDK from other vendors.

**Comment by apangin** [comment] 2022-09-16 23:16
It seems like `-rpath` is not set correctly in Homebrew JDK binaries: in particular, `libjvm.dylib` does not appear on `@rpath`. This results in failures when calling `dlopen` on JDK libraries from async-profiler.

I found a related issue reported previously: https://github.com/Homebrew/homebrew-core/issues/66953
Unfortunately, it has never been fixed.

I committed a workaround in async-profiler. Please try if it helps.

**Comment by deejgregor** [comment] 2022-09-17 02:03
I just ran into this problem today on OpenNMS with Homebrew OpenJDK 11.0.6 and your patch, @apangin, fixes it for me. Thanks! Now, onto debugging what brought me here. :)

**Comment by deejgregor** [comment] 2022-09-22 15:45
FYI, the underlying problem in Homebrew OpenJDK has been addressed: https://github.com/Homebrew/homebrew-core/pull/111255

**Closed** 2022-09-22 16:10 UTC
