### ISSUE TITLE
Higher Java Process RSS than Heap,stack Footprint - Need suggestion around next steps to debug

### ISSUE THREAD

**Issue by khatwaniNikhil** [jvm-profiling-tools/async-profiler#389] opened 2021-02-15 08:41 UTC
Hi,
Thanks for building async profiler. I need some support for the use case - java process RSS memory 2-4GB higher than heap, stack allocations as per jstat. RSS stays almost constant. Details are as follows:

1) Using an ec2 instance with 32G RAM and JAVA 8 (open jdk)

uname -a

Linux app1.xxxxxxxx.infra 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

2) Memory metrics
Heap & Stack(meta space allocation) 
sudo jstat -gc 21850 |awk 'NR==2{split($0,a," "); sum=(a[3]+a[4]+a[6]+a[8]+a[10]+a[12])/1000000; print sum}'
5.7296

Java process RSS footprint
ps -eo pid,rss | grep 21850 | cut -d ' ' -f 2
9335292 (9.3 GB)

3) Jxray report (might not exactly match to above jstat heap metrics, heap dump taken few hours before)
[https://drive.google.com/file/d/1_OB0YemioZv8OF3R8YgGpkAcg7w284TS/view?usp=sharing](jxray report)

Report says
Off-heap memory used by java.nio.DirectByteBuffers.  no significant overhead

4) Read article by Misha Dmitriev https://dzone.com/articles/troubleshooting-problems-with-native-off-heap-memo
section 3 Linux GLIBC Allocator Side-Effects: RSS Grows Big in 64MB Increments
It is suggested to Simply switching to a different Linux distribution, such as CentOS, may be the quickest way to address this problem.
Already on CentOS linux.

5) Async profiler
watched your video also, RSS is somewhat fixed after starup of java process. I am not sure which event to monitor: alloc, malloc, mprotect ?

Any suggestions will be very helpful.
Thanks
Nikhil

**Comment by franz1981** [comment] 2021-02-15 08:43
The application being profiled is using Netty?
Consider that there are frameworks that allocate native memory without being accounted by the JVM  and Netty OOTB does it.

**Comment by krzysztofslusarski** [comment] 2021-02-15 08:46
Nice video in english https://www.youtube.com/watch?v=c755fFv1Rnk

You can check some of these memory segments in JMX. To track it wit more details you can use NMT (native memory tracking).

If you want to use async-profiler check https://github.com/jvm-profiling-tools/async-profiler/issues/341
I like to use page-faults event

**Comment by khatwaniNikhil** [comment] 2021-02-15 09:17
@franz1981 Thanks, apache tomcat is used by the application being profiled. Do i need to still consider native memory without being accounted by the JVM, can u please confirm

**Comment by franz1981** [comment] 2021-02-15 09:22
@khatwaniNikhil Not familiar with Tomcat :)
Only an histogram/heapdump would know: search for *netty* stuff into it and you can check if it can still be possible :+1:

**Comment by khatwaniNikhil** [comment] 2021-02-15 10:31
@franz1981 histogram has no netty stuff
@krzysztofslusarski  JMX output via jmxterm cli tool
$>get HeapMemoryUsage
#mbean = java.lang:type=Memory:
HeapMemoryUsage = { 
  committed = 9179234304;
  init = 536870912;
  max = 11699486720;
  used = 5381737016;
 };

$>get NonHeapMemoryUsage
#mbean = java.lang:type=Memory:
NonHeapMemoryUsage = { 
  committed = 457023488;
  init = 2555904;
  max = -1;
  used = 387540264;
 };
Above output does not looks much helpful to further debug

$>domain java.nio
#domain is set to java.nio
$>beans
#domain = java.nio:
java.nio:name=direct,type=BufferPool
java.nio:name=mapped,type=BufferPool

unable to track "java.nio" domain beans
$>bean java.nio:type=BufferPool
#IllegalArgumentException: Bean name java.nio:type=BufferPool isn't valid

Couple of doubts
1) Any idea/suggestions around of performance impacts of turning on NMT on production ?
2) Can u please suggest some pointers to look for "page-faults event" with async profiler.
3) Also, looks like it need jvm debug symbols install, any idea/suggestions of performance impact on production ?

**Comment by franz1981** [comment] 2021-02-15 10:35
@khatwaniNikhil 

I don't get where the problem is, your prev answer was

`Java process RSS footprint...9335292 (9.3 GB)`

And now:
`$>get HeapMemoryUsage...committed = 9179234304`
+
`$>get NonHeapMemoryUsage...committed = 457023488`

They seems pretty right no?

**Comment by khatwaniNikhil** [comment] 2021-02-15 10:46
@franz1981 Sorry for the confusion and thanks for taking out time to reply. I think i wrongly understood, RSS of java process = total used memory. It should be total committed memory, is this correct ?

**Comment by franz1981** [comment] 2021-02-15 10:52
>I think i wrongly understood, RSS of java process = total used memory. It should be total committed memory, is this correct ?

RSS is what's stand from the OS point of view (that means the allocator too), while the `committed` one reported by Java tools are from the point of view of the JVM and they can differ (due to allocator fragmentation and due to native memory allocated outside the JVM scope eg JNI or using directly Unsafe AFAIK), but it doesn't seem your case, really :)

**Closed** 2021-02-15 11:00 UTC

**Comment by mkaranth-tech** [comment] 2023-10-12 08:55
> Nice video in english https://www.youtube.com/watch?v=c755fFv1Rnk
> 
> You can check some of these memory segments in JMX. To track it with more details you can use NMT (native memory tracking).
> 
> If you want to use async-profiler check #341 I like to use page-faults event
@krzysztofslusarski once we capture page-faults events, what to look for in flame graph to say what is causing NM leak or is major contributor for off-heap RSS memory?
