### ISSUE TITLE
Allocation profiling crashes on Azul Platform Prime

### ISSUE THREAD

**Issue by ZyablitskiyA** [jvm-profiling-tools/async-profiler#632] opened 2022-08-09 12:16 UTC
Hello Async profiler developers!

async-profiler version: at least 2.8.3
Prime (Zing) version: 22.07 JDK11+

We observe a crash in our internal testing with the following backtrace:

0  0x00007f63f3354f47 in raise () from /lib/x86_64-linux-gnu/libc.so.6
1  0x00007f63f33568b1 in abort () from /lib/x86_64-linux-gnu/libc.so.6
2  0x00007f63f0e46f2f in os::abort (dump_core=dump_core@entry=true, out_of_memory=out_of_memory@entry=false) at src/os/linux/os_linux.cpp:3248
3  0x00007f63f1775162 in VMError::report_and_die (this=this@entry=0x7f63e9dfead0) at src/share/utilities/vmError.cpp:1119
4  0x00007f63f174506b in report_vm_error (file=file@entry=0x7f63f2494ff0 "src/azshare/gc_implementation/shared/lvb.hpp", line=line@entry=202, error_msg=error_msg@entry=0x7f63f2494fb0 "assert0((!VerifyJVMLockAtLVB) || verify_jvm_lock()) failed",
    detail_msg=detail_msg@entry=0x7f63f2494f78 "[(!VerifyJVMLockAtLVB) || verify_jvm_lock() expected]", error_type=error_type@entry=INTERNAL_ERROR) at src/share/utilities/debug.cpp:257
5  0x00007f63f17449b2 in report_vm_error (file=file@entry=0x7f63f2494ff0 "src/azshare/gc_implementation/shared/lvb.hpp", line=line@entry=202, error_msg=error_msg@entry=0x7f63f2494fb0 "assert0((!VerifyJVMLockAtLVB) || verify_jvm_lock()) failed",
    detail_msg=detail_msg@entry=0x7f63f2494f78 "[(!VerifyJVMLockAtLVB) || verify_jvm_lock() expected]", error_type=error_type@entry=INTERNAL_ERROR) at src/share/utilities/debug.cpp:259
6  0x00007f63f0a7890a in LVB::lvb<(OopHelper::EncodingHint)1> (addr=0x7f63e9dffa58) at src/azshare/gc_implementation/shared/lvb.hpp:202
7  LVB::lvb<(OopHelper::EncodingHint)1> (addr=0x7f63e9dffa58) at src/azshare/gc_implementation/shared/lvb.hpp:80
8  lvb_methodOop_stack_addr (addr=0x7f63e9dffa58) at src/azshare/gc_implementation/shared/lvb.hpp:174
9  frame::interpreter_frame_method (this=<optimized out>) at src/share/runtime/frame.inline.hpp:98
10 0x00007f63f148d680 in vframe::method (this=0x7f63e9dfed40) at src/share/runtime/vframe.inline.hpp:153
11 JvmtiEnvBase::get_stack_trace (this=this@entry=0x0, java_thread=java_thread@entry=0x620000000000, start_depth=<optimized out>, max_count=max_count@entry=2048, frame_buffer=frame_buffer@entry=0x7f62b40f91b0, count_ptr=count_ptr@entry=0x7f63e9dff1b0)
    at src/share/prims/jvmtiEnvBase.cpp:896
12 0x00007f63f1478734 in JvmtiEnv::GetStackTrace (this=0x0, java_thread=0x620000000000, start_depth=0, max_frame_count=2048, frame_buffer=0x7f62b40f91b0, count_ptr=0x7f63e9dff1b0) at src/share/prims/jvmtiEnv.cpp:1806
13 0x00007f63e93ddf6d in Profiler::recordSample(void*, unsigned long long, int, Event*) () from /src/work/agents/async-profiler-2.8-linux-x64/build/libasyncProfiler.so
14 0x00007f63e93de7ec in ObjectSampler::recordAllocation(_jvmtiEnv*, int, _jclass*, long) () from /src/work/agents/async-profiler-2.8-linux-x64/build/libasyncProfiler.so

This backtrace is from debug build of Prime. On release builds it is also reproducible.

Root cause is getJavaTraceInternal called in a wrong thread state. This API assumes thread state to be "in VM" while when thread comes from object allocation sampling jvmti callback its state is "in native".
getJavaTraceJvmti is the right API for this state.

**Comment by apangin** [comment] 2022-08-09 12:45
`getJavaTraceInternal` was intended for HotSpot only.
It is a bug that it's called in Zing, I'll fix that.

**Comment by apangin** [comment] 2022-08-16 22:16
Thanks for reporting. The fix is committed.

**Closed** 2022-09-16 17:03 UTC
Labels: bug, zing
