### ISSUE TITLE
How to Fight the Unknow_Java Call Stack

### ISSUE THREAD

**Issue by zhengzhuobinzzb** [jvm-profiling-tools/async-profiler#271] opened 2019-11-28 04:31 UTC
My hbase process consumes a lot of CPU (48 core physical machine, cost 4800% cpu_user). When I use async-profiler to locate the problem, I find a lot of unknown_Java occupation. In addition, other stacks show up normally. What's good Solution, can unknown_Java display its corresponding call stack?

**I started under the root user, and the startup command was:**
./profiler.sh -d 30 62663

**The version used is:**
async-profiler-1.6-ea-linux-x64.tar.gz

**The kernel version is:**
uname -a
Linux XXX 3.10.0-327.el7.x86_64 # 1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU / Linux

**Analysis results:**

Started [cpu] profiling
--- Execution profile ---
Total samples: 135166
unknown_Java: 103087 (76.27%)
not_walkable_Java: 34 (0.03%)
skipped: 68 (0.05%)

Frame buffer usage: 6.7833%

--- 1024431079937 ns (75.90%), 102552 samples
  [0] [unknown_Java]

--- 19858600281 ns (1.47%), 1988 samples
  [0] org.apache.hadoop.hbase.KeyValue $ KVComparator.compare
  [1] java.util.concurrent.ConcurrentSkipListMap.cpr
  [2] java.util.concurrent.ConcurrentSkipListMap.findPredecessor
  [3] java.util.concurrent.ConcurrentSkipListMap.doPut
  [4] java.util.concurrent.ConcurrentSkipListMap.put
  [5] org.apache.hadoop.hbase.regionserver.CellSkipListSet.add
  [6] org.apache.hadoop.hbase.regionserver.DefaultMemStore.addToCellSet

.......
          ns percent samples top
  ---------- ------- ------- ---
1024431079937 75.90% 102552 [unknown_Java]
 29288543324 2.17% 2932 org.apache.hadoop.hbase.util.Bytes $ LexicographicalComparerHolder $ UnsafeComparer.compareTo
 28639252591 2.12% 2867 org.apache.hadoop.hbase.KeyValue $ KVComparator.compare
 23026109960 1.71% 2305 org.apache.hadoop.hbase.KeyValue.getFamilyLength
 14514725503 1.08% 1453 org.apache.hadoop.hbase.util.Bytes.toShort

**Comment by zhengzhuobinzzb** [comment] 2019-11-28 04:34
If anyone can help explain how unknow_Java was formed, thanks a lot.

**Comment by zhengzhuobinzzb** [comment] 2019-11-28 04:58
**Jvm Version:**
1.8.0_121
**JVM Options**
java -Dproc_regionserver -XX:OnOutOfMemoryError=kill -9 %p -XX:MaxDirectMemorySize=80G -XX:+HeapDumpOnOutOfMemoryError -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/data1/hbase/logs/hbase.gc -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=512M -Xmx80g -Xms80g -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=400 -XX:G1NewSizePercent=2 -XX:InitiatingHeapOccupancyPercent=65 -XX:+ParallelRefProcEnabled -XX:ConcGCThreads=4 -XX:ParallelGCThreads=16 -XX:MaxTenuringThreshold=15 -XX:G1HeapRegionSize=32m -XX:G1MixedGCCountTarget=64 -XX:G1OldCSetRegionThresholdPercent=5 -XX:MaxDirectMemorySize=85G -verbose:gc -XX:+PrintGCDetails -XX:+PrintAdaptiveSizePolicy -XX:+PrintGCDetails -XX:+PrintGCApplicationStoppedTime -XX:+PrintTenuringDistribution -XX:+PrintGCTimeStamps -XX:+UnlockDiagnosticVMOptions -XX:+LogCompilation -XX:LogFile=/data1/hbase/logs/compile.log -Dhbase.log.dir=/data1/hbase/logs -Dhbase.log.file=hbase.log -Dhbase.root.logger=INFO,RFA -Dhbase.security.logger=INFO,RFAS org.apache.hadoop.hbase.regionserver.HRegionServer start

**Comment by apangin** [comment] 2019-11-28 20:23
This is indeed strange.
Seems like you use early access version of async-profiler. What about the latest 1.6?
Also, what exactly JDK build are you running?
```
java -version
java -Xinternalversion
```

Does profiling work with other apps? E.g. does `make test` complete successfully?

**Comment by zhengzhuobinzzb** [comment] 2019-12-02 06:52
The version what i used is the latest version: **async-profiler-1.6-ea-linux-x64.tar.gz** .
 
**java -version**
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

 **java -Xinternalversion**
Java HotSpot(TM) 64-Bit Server VM (25.121-b13) for linux-amd64 JRE (1.8.0_121-b13), built on Dec 12 2016 16:36:53 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)

profiler with simple test Of test/Target can't found unknow_Java. 
result is :
         ns  percent  samples  top
  ----------  -------  -------  ---
  7181012427   36.35%      718  Target.method1
  7141017335   36.15%      714  Target.method2
   379955071    1.92%       38  jni_SetObjectArrayElement
   300028775    1.52%       30  jni_invoke_nonstatic(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)
   260388687    1.32%       26  filldir_[k]
   259997139    1.32%       26  java.lang.StringCoding$StringDecoder.decode
   209974560    1.06%       21  HandleMarkCleaner::~HandleMarkCleaner()
   199994198    1.01%       20  jni_DeleteLocalRef

**Comment by apangin** [comment] 2019-12-03 23:53
I'll try to investigate. But this will be probably hard without a test case. If you manage to get a self-contained example that I can reproduce on my side, this will be very helpful.

**Comment by apangin** [comment] 2019-12-08 21:31
I've built an experimental version with the special treatment of `unknown_Java` samples.
Please, give it a try and tell if the things get better.
Please also send the stacktraces containing `unknown_Java` to me for the further investigation.
Thanks.
Here is the new build: [async-profiler-1.6-special-linux-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/files/3937146/async-profiler-1.6-special-linux-x64.tar.gz)

**Comment by kpdsquare** [comment] 2019-12-10 11:18
I'm also having an issue identifying unknown_Java stacks with the latest release. I'm not sure if my issue is related, however, below you will see a zoomed in part of a flame graph by thread (using -t async-profiler switch), but what I find strange is that the Thread.run() method is not taking up the whole of the T-EventHandlingThread-1 function, and furthermore, there is nothing else occupying the remaining space. I assumed that the empty space should have been taken up by some unknown_Java stack after looking at a summary file.

![image](https://user-images.githubusercontent.com/36452344/70524954-2f144000-1b3e-11ea-83bd-46b1c05e766f.png)

I then used the special build you created and it appears as though I can now see unknown_Java stacks as shown in the second flame graph. Please excuse my ignorance, but are those unknown_Java stacks due to JIT compilations or something else? Also why would the unknown_Java stacks be above T-EventHandling-Thread-1? Should it not be somewhere above Thread.run()?

![image](https://user-images.githubusercontent.com/36452344/70525133-8b775f80-1b3e-11ea-8049-ecada7ef567f.png)

P.S. Great job with async-profiler. It's been very helpful in finding problems.

**Comment by apangin** [comment] 2019-12-10 13:06
@kpdsquare `unknown_Java` denotes the cases when Java code was running, but VM wan't able to traverse the stack (possibly because of the non-standard stack frame layout or a frame in some transition state). I'm not sure about the reasons, so this is where I need your help (since I've fixed almost all `unknown_Java` cases observed in my own experiments).

- Are there the same `unknown_Java` samples when running application on a different Java version?
- What are the methods above `unknown_Java` in the flame graph?
- Does the amount of unknown decrease or increase, if run Java with `-XX:-TieredCompilation` or `-XX:TieredStopAtLevel=1`?

**Comment by kpdsquare** [comment] 2019-12-10 14:53
> Are there the same unknown_Java samples when running application on a different Java version?

Do you mean on a different major version or an update version? I'm currently using the following Java build:

java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

Testing a later major version of Java might take a little longer for me to test. Let me know if this is what you want and I'll see if I can find the time to modify our environment for Java 11.

> What are the methods above unknown_Java in the flame graph?

Above the T-EventHandlingThread-1 frame, I'm getting a small **not_walkable_java** frame (circled in blue below) and then the **unknown_Java** frame. Above the **unknown_Java** frame I see a frame pointing at my own application code. Above the **unknown_walkable_frame** I get an **unknown** frame which calls **__clock_gettime**.

![image](https://user-images.githubusercontent.com/36452344/70539559-c89e1a80-1b5b-11ea-804d-395de4b7fbe1.png)

> Does the amount of unknown decrease or increase, if run Java with -XX:-TieredCompilation or -XX:TieredStopAtLevel=1?

In my case I was not getting many unknown frames in the first place (around 1.8%-2% from the summary), however, my issue did feel related, so I'm not sure if the following results are going to be helpful.

**These tests are with the special build (1.6-special):**
**A1:** My run with -XX:-TieredCompilation displayed an **unknown_Java** frame above the T-EventHandlingThread-1 frame, then a small **unknown** frame and my application frame above.

![image](https://user-images.githubusercontent.com/36452344/70538469-0c902000-1b5a-11ea-9be5-6a4c16b517b3.png)

**A2:** My run with -XX:TieredStopAtLevel=1 displayed an **unknown_Java** frame, an Iterable.foreach and a Thread.run frame above the T-EventHandlingThread-1 frame. Above the unknown_Java frame there is a small **unknown** frame and my application frame.

![image](https://user-images.githubusercontent.com/36452344/70540096-8b865800-1b5c-11ea-9683-c3f420fcb606.png)

**These tests are with the latest release build (1.6):**
**B1:** My run with -XX:-TieredCompilation displayed an **unknown** frame above the T-EventHandlingThread-1 frame.
![image](https://user-images.githubusercontent.com/36452344/70538830-a22baf80-1b5a-11ea-8fd8-3bd49fc0d2aa.png)

**B2:** My run with -XX:TieredStopAtLevel=1 displayed the same frames as B1.

**Comment by apangin** [comment] 2019-12-10 17:53
Thank you for the info. In fact, 1-2% of unknown frames are expected, since with asynchronous stack walking the top frame may sometimes appear in a transition/inconsistent state, when it is hard to recover the right call chain. But the problem is when `unknown_Java` takes more than 50% of the profile, like in the original issue.

Does your application frame (on top of unknown_Java) also appear in normal stack traces? Or does it always go together with unknown? It's unfortunate that this frame belongs to the proprietary code - it would be helpful to understand what kind of methods cause such `unknown_Java` situation. If you happen to see a method on top of unknown_Java, which code you may share, I'll be glad to analyse it.

**Comment by kpdsquare** [comment] 2019-12-10 18:31
I was expecting the low percentage of unknown frames to be expected, however, I only started seeing them in the flame graphs with the special build you created. So the special build solves the issue of at least being able to see the unknown frames in the flame graphs. 

The application frame does appear else where, higher up on the stack (very close to the top)  in the flame graph. It might be of interest to you to know that the application frame of interest is a lambda reference for a BiConsumer, that is initialised in the constructor to avoid the BiConsumer being allocated on every call. This BiConsumer is passed to a Map.forEach() call very frequently (a few times every millisecond).

If this isn't enough information to decipher what is causing the unknown_Java, I can try and create some test code to replicate the scenario, which I would then be able to share. Might take a little while for me to get this done though given some time restraints I have.

**Comment by kpdsquare** [comment] 2019-12-10 19:10
To put the above into context, below is an obfuscated pseudo/example code of the method reference I think is causing the unknown_Java frames. Maybe this will be useful until I get around to writing some working example code I can share:

```
private final Map<ClassAEnum, Map<ClassBEnum, Config>> configMap;
private final BiConsumer<ClassA, ClassB> consumer;

public MyClass() {
	consumer = this:myMethodReference;
}

private void onSomeEvent() {
	// Use consumer on Map.forEach()
}

private void myMethodReference(final ClassA a, final ClassB b) {
	final P p = b.s().getP();
	final long dur = a.getDur();
	final Config config = configMap.get(a.getClassAEnum())
			.get(p.getClassBEnum());
	final double amt = config.getAmt();
	final long diff = (System.currentTimeMillis()) - b.r();
	final double ramt = b.ramt();
	b.sv(diff >= dur && Double.compare(ramt, 0) > 0
			&& M.check(ramt, amt, b.s().adp()));
}
```

**Comment by apangin** [comment] 2019-12-10 22:53
@kpdsquare Thank you for the example. I bet in your case `unknown_Java` is mostly caused by `System.currentTimeMillis`.

`System.currentTimeMillis` as well as `System.nanoTime` are [very problematic](https://github.com/jvm-profiling-tools/async-profiler/issues/196#issuecomment-456996146) for reconstruction of async stack traces, since 1) they are JVM intrinsics that call native code without actually switching thread state to native; 2) the target native code does not follow normal frame linking pattern.

This is not a bug of async-profiler - this is just one of those cases when the stack state is not trace-friendly.

To verify that the problem is caused by `System.currentTimeMillis`, you may turn off the intrinsic with the following JVM options:
```
-XX:+UnlockDiagnosticVMOptions -XX:DisableIntrinsic=_currentTimeMillis,_nanoTime
```

**Comment by kpdsquare** [comment] 2019-12-11 11:58
So I realised some of the tests I did yesterday with the tiered compilation flags may have not been applied. For this reason I’ve redone the tests for completeness (see below) along with the intrinsic tests, even if you’re pretty certain of the reasons behind the unknown_Java here.

A summary of the tests from my perspective:
1. With the current 1.6 release build, I'm not even able to see the unknown_Java frames above the T-EventHandlingThread-1 frame. The special build fixes this for me, making it somewhat less confusing for me to see where the CPU cycles are going.
2. Disabling the intrinsics didn't appear to remove the unknown_Java in my test runs.
3. Disabling tiered compilation or stopping at tiered compilation level 1 didn't appear to make any difference.
4. I'm still uncertain if the unknown_Java frames are as a result of the System.currentTimeMillis as you suggested.

Are you going to merge the special build changes you've made into master?

_**These tests are with the special build (1.6-special):**_
**A1:** My run with **-XX:-TieredCompilation** displayed a small **not_walkable_java**, an **unknown_Java**, and a Thread.run frames above the T-EventHandlingThread-1 frame. Above the **unknown_Java** frame there are three frames: Intepreter, and two application frames, one of which is a reference to SomeClass$$Lambda$352/253733343.accept.

![image](https://user-images.githubusercontent.com/36452344/70618607-335a5f00-1c0b-11ea-856e-3bb3afae921e.png)

**A2:** My run with **-XX:TieredStopAtLevel=1** displayed an **unknown_Java** and a Thread.run frames above the T-EventHandlingThread-1 frame. Above the **unknown_Java** frame there is a fpu2long_stub frame which calls into __clock_gettime.

![image](https://user-images.githubusercontent.com/36452344/70618659-54bb4b00-1c0b-11ea-9f46-20147352c2aa.png)

_**These tests are with the latest release build (1.6):**_
**B1:** My run with **-XX:-TieredCompilation** displayed only the Thread.run() frame above T-EventHandlingThread-1 frame, with empty space beside it.

![image](https://user-images.githubusercontent.com/36452344/70618721-73b9dd00-1c0b-11ea-9852-903f8af367b3.png)

**B2:** My run with **-XX:TieredStopAtLevel=1** displayed the same frames as B1.

_**These tests are with the special build (1.6-special):**_
**C1:** My run with **-XX:+UnlockDiagnosticsVMOptions -XX:DisabledIntrinsic=_currentTimeMillis,nanoTime** displayed an **unknown_Java** and Thread.run frame above T-EventHandlingThread-1 frame. Above the **unknown_Java** frame there is a call into my application frame referencing SomeClass$$Lambda$353/1767605733.accept.

![image](https://user-images.githubusercontent.com/36452344/70618771-8fbd7e80-1c0b-11ea-8f05-4148190dfb5b.png)

_**These tests are with the latest release build (1.6):**_
**D1:** My run with **-XX:+UnlockDiagnosticsVMOptions -XX:DisabledIntrinsic=_currentTimeMillis,nanoTime** displayed the same frames as B1.

P.S. Thanks for taking the time to look into this.

**Comment by apangin** [comment] 2019-12-12 00:05
@kpdsquare Thank you for the update. Looks like in your case the source of `unknown_Java` is not `System.currentTimeMillis`. Not sure what else it could be then. Will try to create a reproducer basing on your example.

Meanwhile I've commited the changes from the 'special' build into master.

**Comment by apangin** [comment] 2019-12-16 22:58
@zhengzhuobinzzb I committed several improvements that should reduce the amount of unknown_Java frames. Can you re-check the latest version from master? For your convenience, I prepared a binary build, too: [async-profiler-1.6-21af257-linux-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/files/3970550/async-profiler-1.6-21af257-linux-x64.tar.gz)

**Comment by apangin** [comment] 2020-01-20 22:30
Closing the issue, as the problem has been addressed, and there has been no feedback for more than a month.

**Closed by apangin** 2020-01-20 22:30 UTC

**Comment by felixbarny** [comment] 2020-02-05 14:21
Not sure if this is related but I just found out that there's a very small percentage (~0.5%) of stack traces that don't contain Java frames but only native ones. This seems to be related to deoptimizations. What seems a bit strange is that this happens inside a `java.lang.Thread`, not a VM thread.

This is not a problem for my use case, just wanted to share these findings.

Some examples of the native frames in these cases:

```
TemplateInterpreter::deopt_reexecute_entry
vframeArrayElement::unpack_on_stack
vframeArray::unpack_to_stack
Deoptimization::unpack_frames
deoptimization
```

```
tiny_free_no_lock
free_tiny
Deoptimization::cleanup_deopt_info
Deoptimization::unpack_frames
deoptimization
```

```
default_zone_malloc
malloc
os::malloc
CHeapObj<
CHeapObj<
Deoptimization::fetch_unroll_info_helper
Deoptimization::fetch_unroll_info
deoptimization
```

**Comment by apangin** [comment] 2020-02-05 19:41
@felixbarny Yes, this is an expected behavior. Deoptimization is a process of replacing Compiled frames with Interpreter frames right on the Java stack of a running application. This indeed happens in the context of the working Java thread: basically, JVM deliberately trashes the stack where it currently runs :) No surprise, that in the middle of this process the stack is not walkable.

This should not happen often in a normal application. It's safe to ignore such samples.
