### ISSUE TITLE
Consider deploying async-profiler to maven central with bundled native library

### ISSUE THREAD

**Issue by victornoel** [jvm-profiling-tools/async-profiler#627] opened 2022-08-04 08:59 UTC
Hi,

This would be really cool to have the latest version of async-profiler deployed to maven central (right now the old 1.8.3 version is there, which is good enough for experimenting) and also having jar bundling the native libraries for easy inclusion by projects.

My personal use case is that I want to add profiling capabilities to a Java project that runs heavy calculations and outputs its results as files and data. So we would output the flamegraph along those quite naturally.

Right now I have to ship the lib myself in the jar to make this work. And hack around the `AsyncProfiler` class (from 1.8.3 since it's the only thing I can include in maven) to create the singleton without triggering the call to `System.loadLibrary`.

A good idea is to use https://github.com/scijava/native-lib-loader as a way to load the library from the jar (because `System.loadLibrary` does not support loading libs from a jar out of the box).

There exists also https://github.com/maven-nar/nar-maven-plugin to bundle such jar, but I suspect that in the specific case of async-profiler, it's just better to have the compilation of the lib done separately as you already do :)

**Comment by apangin** [comment] 2022-08-04 09:16
Thanks for your input.
Since there is already a similar issue, let me link and close your one.

Duplicate of #93

**Closed by apangin** 2022-08-04 09:16 UTC

**Comment by victornoel** [comment] 2022-09-26 14:59
@apangin is there any way to at least get version 2.8.3 deployed to maven central, as-is? The currently available version is 1.8.3 and it does not contain some of the fixes present in the latest version in the git repository, in particular allow to use getInstance when the lib is already loaded: https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/api/one/profiler/AsyncProfiler.java#L47

Thanks!

**Comment by apangin** [comment] 2022-09-26 21:07
@victornoel The task is planned, but has not been assigned to a particular release yet.

**Comment by victornoel** [comment] 2022-09-27 06:31
@apangin ok, and it's not possible to just deploy 2.8.3 as-is already?

**Comment by apangin** [comment] 2022-10-01 07:26
I don't have a "just deploy" button, sorry. Publication of existing binaries takes some efforts anyway. I'll do that when preparing a new release (that should happen shortly).

**Comment by victornoel** [comment] 2022-10-01 11:40
Ok, I better understand now, thank you for the explanation!
