### ISSUE TITLE
Getting some warnings on start

### ISSUE THREAD

**Issue by asifansari80** [jvm-profiling-tools/async-profiler#148] opened 2018-07-30 11:10 UTC
Hi
I am getting following warnings:
WARNING: couldn't find container pid of the target process
WARNING: couldn't enter target process mnt namespace

Can it be ignored ?

Also, is there any KB for interpreting the results of this usefull tool.
Thanks
Asif

**Comment by apangin** [comment] 2018-07-30 12:48
Does profiler work despite the warnings?

What results are you asking about? Is it the text output? Profiler supports multiple output formats: flame graph (svg), call tree (html), etc.

**Comment by apangin** [comment] 2018-07-30 16:23
There should not be warnings in normal profiler operation. Please run

    strace build/jattach <pid> jcmd help

and send me the output to help me find the reason.

**Comment by apangin** [comment] 2018-07-30 16:32
The default output consists of the flat profile (the historgram of top 200 hot methods) and top 200 hot stacktraces. I suggest to start with Flame Graph ouput instead: `-f output.svg`. This will produce a nice interactive visualization that can be viewed in a browser.

There is a [great site devoted to Flame Graphs](http://www.brendangregg.com/flamegraphs.html).

**Comment by asifansari80** [comment] 2018-08-02 05:38
Here is the needed o/p:
-sh-4.1$ hostname
PSUP3

-sh-4.1$ /opt/tpa/java/bin/jps
11357 WatchDog
14455 Main
16740 Jps
-sh-4.1$ strace build/jattach 14455 jcmd help
execve("build/jattach", ["build/jattach", "14455", "jcmd", "help"], [/* 21 vars */]) = 0
brk(0)                                  = 0x2496000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe5c4ca3000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("tls/x86_64/libc.so.6", O_RDONLY)  = -1 ENOENT (No such file or directory)
open("tls/libc.so.6", O_RDONLY)         = -1 ENOENT (No such file or directory)
open("x86_64/libc.so.6", O_RDONLY)      = -1 ENOENT (No such file or directory)
open("libc.so.6", O_RDONLY)             = -1 ENOENT (No such file or directory)
open("/opt/tpa/timesten/TimesTen/tpa/lib/tls/x86_64/libc.so.6", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/opt/tpa/timesten/TimesTen/tpa/lib/tls/x86_64", 0x7ffd1a4514c0) = -1 ENOENT (No such file or directory)
open("/opt/tpa/timesten/TimesTen/tpa/lib/tls/libc.so.6", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/opt/tpa/timesten/TimesTen/tpa/lib/tls", 0x7ffd1a4514c0) = -1 ENOENT (No such file or directory)
open("/opt/tpa/timesten/TimesTen/tpa/lib/x86_64/libc.so.6", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/opt/tpa/timesten/TimesTen/tpa/lib/x86_64", 0x7ffd1a4514c0) = -1 ENOENT (No such file or directory)
open("/opt/tpa/timesten/TimesTen/tpa/lib/libc.so.6", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/opt/tpa/timesten/TimesTen/tpa/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/etc/ld.so.cache", O_RDONLY)      = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=23428, ...}) = 0
mmap(NULL, 23428, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fe5c4c9d000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY)      = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\356\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1924768, ...}) = 0
mmap(NULL, 3750184, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fe5c46f1000
mprotect(0x7fe5c487b000, 2097152, PROT_NONE) = 0
mmap(0x7fe5c4a7b000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18a000) = 0x7fe5c4a7b000
mmap(0x7fe5c4a81000, 14632, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fe5c4a81000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe5c4c9c000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe5c4c9b000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe5c4c9a000
arch_prctl(ARCH_SET_FS, 0x7fe5c4c9b700) = 0
mprotect(0x7fe5c4a7b000, 16384, PROT_READ) = 0
mprotect(0x602000, 4096, PROT_READ)     = 0
mprotect(0x7fe5c4ca4000, 8192, PROT_READ) = 0
munmap(0x7fe5c4c9d000, 23428)           = 0
geteuid()                               = 500
getegid()                               = 500
brk(0)                                  = 0x2496000
brk(0x24b7000)                          = 0x24b7000
open("/proc/14455/status", O_RDONLY)    = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe5c4ca2000
read(3, "Name:\tjava\nState:\tS (sleeping)\nT"..., 1024) = 908
read(3, "", 1024)                       = 0
close(3)                                = 0
munmap(0x7fe5c4ca2000, 4096)            = 0
stat("/proc/self/ns/pid", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/14455/ns/pid", 0x7ffd1a44f660) = -1 EACCES (Permission denied)
open("/proc/14455/root/proc", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 EACCES (Permission denied)
write(2, "WARNING: couldn't find container"..., 59WARNING: couldn't find container pid of the target process
) = 59
open("/proc/self/ns/mnt", O_RDONLY)     = 3
open("/proc/14455/ns/mnt", O_RDONLY)    = -1 EACCES (Permission denied)
write(2, "WARNING: couldn't enter target p"..., 53WARNING: couldn't enter target process mnt namespace
) = 53
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7fe5c4723660}, {SIG_DFL, [], 0}, 8) = 0
stat("/tmp/.java_pid14455", {st_mode=S_IFSOCK|0600, st_size=0, ...}) = 0
socket(PF_LOCAL, SOCK_STREAM, 0)        = 4
connect(4, {sa_family=AF_LOCAL, sun_path="/tmp/.java_pid14455"}, 110) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe5c4ca2000
write(1, "Connected to remote JVM\n", 24Connected to remote JVM
) = 24
write(4, "1\0", 2)                      = 2
write(4, "jcmd\0", 5)                   = 5
write(4, "help\0", 5)                   = 5
write(4, "\0", 1)                       = 1
write(4, "\0", 1)                       = 1
write(1, "Response code = ", 16Response code = )        = 16
read(4, "0\nThe following commands are ava"..., 8191) = 378
write(1, "0\nThe following commands are ava"..., 3780
The following commands are available:
VM.native_memory
VM.commercial_features
GC.rotate_log
ManagementAgent.stop
ManagementAgent.start_local
ManagementAgent.start
Thread.print
GC.class_histogram
GC.heap_dump
GC.run_finalization
GC.run
VM.uptime
VM.flags
VM.system_properties
VM.command_line
VM.version
help

For more information about a specific command use 'help <command>'.
) = 378
read(4, "", 8192)                       = 0
write(1, "\n", 1
)                       = 1
close(4)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
-sh-4.1$

**Comment by asifansari80** [comment] 2018-08-02 11:39
Do i need to run it as root ?

**Comment by apangin** [comment] 2018-08-02 12:51
That's fine, thank you.
In your case the profiler seems to work well, and the warnings can be ignored. I will look how to remove false warnings (the problem is they are not always false).

**Comment by apangin** [comment] 2018-08-06 23:08
False warnings have been fixed in the upcoming release.

**Closed by apangin** 2018-08-06 23:08 UTC
