### ISSUE TITLE
Stack frames sometimes appear at the wrong nesting level

### ISSUE THREAD

**Issue by oehme** [jvm-profiling-tools/async-profiler#454] opened 2021-09-07 05:55 UTC
Given the following code:

```
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class LineNumberProblem {

    public static void main(String[] args) {

        LongThing seed = new LongThing(1);
        List<Thing> things = Stream.iterate(seed, LineNumberProblem::next).limit(100000).collect(Collectors.toList());

        while (true) {
            Thing previousThing = seed;
            long result = 0;
            for (Thing thing : things) {
                result += Long.compare(previousThing.getAsLong(), thing.getAsLong());
                previousThing = thing;
            }
            System.out.println(result);
        }
    }

    private static Thing next(Thing previous) {
        if (previous instanceof LongThing) {
            return new DoubleThing(1.0);
        } else if (previous instanceof DoubleThing) {
            return new BooleanThing(true);
        } else if (previous instanceof BooleanThing) {
            return new IntThing(2);
        } else {
            return new LongThing(1);
        }
    }

    public interface Thing {
        long getAsLong();
    }

    static class LongThing implements Thing {
        private final long data;

        public LongThing(long data) {
            this.data = data;
        }

        @Override
        public long getAsLong() {
            return data;
        }
    }

    static class IntThing implements Thing {
        private final int data;

        public IntThing(int data) {
            this.data = data;
        }

        @Override
        public long getAsLong() {
            return data;
        }
    }

    static class DoubleThing implements Thing {
        private final double data;

        public DoubleThing(double data) {
            this.data = data;
        }

        @Override
        public long getAsLong() {
            return (long) data;
        }
    }

    static class BooleanThing implements Thing {
        private final boolean data;

        public BooleanThing(boolean data) {
            this.data = data;
        }

        @Override
        public long getAsLong() {
            return data ? 1 : 0;
        }
    }

}

``` 

The flame graph shows `getAsLong` inside `Long.compare`. It should be directly under `LineNumberProblem:15` instead.
![linenumber-problem](https://user-images.githubusercontent.com/1191797/132259848-a9683d71-e702-4d06-b656-1dbe72d15a78.png)

**Comment by apangin** [comment] 2021-09-07 23:40
Thanks for the test case. I can confirm the bug.

Sometimes JVM incorrectly attributes compiled machine to the original bytecode, but in this case it's async-profiler's fault.
How to check: add `--safe-mode 255` option. If an invalid stack trace remains, this is a JVM bug. If invalid stack traces disappear (resulting in `[unknown_Java]` frames), this is an async-profiler problem.

**Comment by apangin** [comment] 2021-09-08 00:19
I committed the fix that significantly reduces the chance of the issue.

There still can be rare situations when async-profiler reconstructs an impossible stack, but fixing those would be dangerous, as improper manipulation with addresses can lead to the JVM crash. I'll better stay safe for now, and investigate this deeper some time later. At least, I can probably mark the recovered stack traces somehow, so that the suspicious stacks are highlighted in the flame graph.

**Comment by oehme** [comment] 2021-09-08 07:49
Thank you for the quick fix Andrei! Just tried it on the real app that I had trouble with and the top frames make a lot more sense now :)

**Comment by apangin** [comment] 2021-09-30 01:47
Closing the issue, since the main problem is fixed.

**Closed by apangin** 2021-09-30 01:47 UTC
Labels: bug
