### ISSUE TITLE
Potential crash when running async-profiler while already active

### ISSUE THREAD

**Issue by liorgorb** [jvm-profiling-tools/async-profiler#395] opened 2021-03-08 16:00 UTC
There is an issue when running async-profiler while it's already started in another session. I haven't dug into all repercussions of this, but one of them can be reproduced by starting profiler.sh in `itimer` mode, then while it is still running, starting it in `cpu` mode. As a result, `PerfEvents::signalHandler` will catch the `SIGPROF`. Since it doesn't expect the signal caused by the `itimer` mechanism, this results in unexpected behavior.

I tested this scenario on a test program that writes to stdout and runs as a daemon, and it resulted in `PerfEvents::signalHandler` calling `read(siginfo->si_fd, ...)`, which resulted in `SIGTTIN` since `si_fd` was 0.

Easiest solution would probably be to detect async-profiler is already running and return an error.

**Comment by apangin** [comment] 2021-03-09 00:13
Could you please elaborate on how you got this crash?
async-profiler already has the protection from starting twice.

When I ran `profiler.sh start -e itimer` and then `profiler.sh start -e cpu`, I expectedly got
```
[ERROR] Profiler already started
```

**Comment by apangin** [comment] 2021-03-09 00:13
Could you please elaborate on how you got this crash?
async-profiler already has the protection from starting twice.

When I run `profiler.sh start -e itimer` and then `profiler.sh start -e cpu`, I expectedly get
```
[ERROR] Profiler already started
```

**Comment by liorgorb** [comment] 2021-03-09 09:38
Oh, I see... I'm using async-profiler from 2 different paths, so the `so` gets loaded twice, hence the protection in place doesn't work.

**Comment by apangin** [comment] 2021-03-10 23:06
OK. So, this doesn't differ much from a case when multiple incompatible libraries are loaded together in one process.
I don't think async-profiler needs to do something in this respect: the fix won't be trivial, while the benefit is questionable. Disallowing multiple instances of the profiler is not an option - I know such configuration is used.

In view of the above, let me just close the issue as `not a bug`.

**Closed by apangin** 2021-03-10 23:06 UTC

**Comment by Jongy** [comment] 2021-03-13 19:21
If I understand correctly, the issue is that a signal handler was called with inappropriate arguments. Two different `libasyncProfiler.so` have installed 2 different handlers for `SIGPROF` which read the arguments differently. Had the second invocation checked before whether a handler for `SIGPROF` is already in place, it could tell someone is already profiling, and refuse continuing?

**Comment by apangin** [comment] 2021-03-13 22:58
@Jongy Yes, but not that trivial.
There is no way to unload a JVM TI agent. If I decide to upgrade async-profiler without restarting the target process, the only possibility to do that is to load the second agent. However, the second agent will refuse to work when it sees that SIGPROF handler has been already set by the first agent.

The signal handler is just one side of the problem. The profiler does other exclusive things to the JVM that may conflict with other agents. For example, there is Java method profiling mode that does not rely on signal handlers at all, but still cannot be used by two agents simultaneously.

While it is possible to come up with a proper protocol for conflict resolution, I wouldn't like to overcomplicate things just to solve a rare misuse problem. Just don't run two agents concurrently, and everything will be fine.
