### ISSUE TITLE
frequent  No such file or directory when using jfrsync

### ISSUE THREAD

**Issue by cfraenkel** [jvm-profiling-tools/async-profiler#657] opened 2022-10-12 18:49 UTC
I'm getting frequent `[WARN] Failed to open JFR recording at ...` when running async-profiler as an agent on process exit. When I check for the recording the JFR file exists and contains jfr events but no data from async profiler. On some runs everything works and I get a jfr output file with both events and profiling data.

I use the folloing jvm arguments:
```
-agentpath:/opt/async-profiler/build/libasyncProfiler.so=start,event=itimer,loop=1h,file=/home/jenkins/agent/workspace/Sandbox/job/recording-second-%p-%t.jfr,jfrsync=/home/jenkins/agent/workspace/Sandbox/job/acs-profiling.jfc,threads
```

I'm using async-profiler-2.8.3-linux-x64 and the following java:
```
openjdk version "11.0.16.1" 2022-08-12
OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode, sharing)
```

The process runs as part of a jenkins pipeline inside a kubernetes container.

```
[WARN] Failed to open JFR recording at /home/jenkins/agent/workspace/Sandbox/job/recording-second-100420-20221012-191159.jfr: No such file or directory
````

**Comment by apangin** [comment] 2022-10-12 20:26
The problem is understood; I'll work on a fix.

**Comment by apangin** [comment] 2022-10-12 21:35
Timestamp placeholder `%t` in the file name was independently expanded twice: for the JDK Flight Recording and for the async-profiler recording. This could happen at different seconds resulting in different file names.

I committed the fix.

**Comment by cfraenkel** [comment] 2022-10-13 18:40
great, thanks for looking into it and fixing it that fast

**Closed** 2022-11-27 02:15 UTC
Labels: bug
