### ISSUE TITLE
show detailed info in stacktrace

### ISSUE THREAD

**Issue by ismlsmile** [jvm-profiling-tools/async-profiler#59] opened 2017-10-16 08:34 UTC
I mean the actual filename and source line number should be showed, like:
Counter: 5871 (51.35%)
  [ 0] jshort_disjoint_arraycopy( XXX.java: xx)
  [ 1] java.util.Arrays.copyOf( XXX.java: xx)
  [ 2] java.lang.AbstractStringBuilder.ensureCapacityInternal( XXX.java: xx)
  [ 3] java.lang.AbstractStringBuilder.append( XXX.java: xx)
  [ 4] java.lang.StringBuilder.append( XXX.java: xx)
  [ 5] com.company.Main.main( Main.java: 12)

Thus it is easy to debug which line code is the problem.

**Comment by apangin** [comment] 2017-10-17 10:11
Bytecode information is deliberately stripped from the frames in order to reduce the number of different stack traces. Adding this information back will result in considerable performance and memory overhead without providing much value for analysis.

If you are OK to create a pull request for this feature, I'll leave this issue open. Otherwise I'm inclined to close it as "will not fix".

**Closed by apangin** 2017-10-17 10:11 UTC

**Comment by nitsanw** [comment] 2017-10-17 10:26
FYI, this is implemented in honest-profiler, but there the conversion from bci to loc is done out of sample. Adding this functionality to AP will increase sample overhead and footprint considerably, and as @apangin points out is often not required. If one was to implement this feature I'd argue for annotating only the top methods (so reduce the number of bci to loc conversions).

**Comment by apangin** [comment] 2020-10-25 22:26
async-profiler 2.0 now preserves bytecode indices and line numbers in JFR output format.

**Comment by oehme** [comment] 2021-09-04 21:36
Is there some way to get a flame graph with these line numbers when using the JFR format? I tried the converter.jar, but that gives me a graph without line numbers.

**Comment by apangin** [comment] 2021-09-06 01:03
@oehme I committed the update to the converter that adds line numbers / bytecode indices to a Flame Graph.

`jfr2flame` now accepts two additional options:
 - `--lines` to add line numbers;
 - `--bci` to add bytecode indices.

Note that line/bci information might not be always accurate for the topmost compiled frames.

**Comment by oehme** [comment] 2021-09-06 09:50
Thank you for the quick help!

**Comment by oehme** [comment] 2021-09-06 09:53
> Note that line/bci information might not be always accurate for the topmost compiled frames.

Is that accuracy lost due to inlining? I've noticed recently that sometimes methods show up nested inside each other, even though in the code they are sibblings. Is that related?

**Comment by apangin** [comment] 2021-09-06 18:43
> Is that accuracy lost due to inlining? I've noticed recently that sometimes methods show up nested inside each other, even though in the code they are sibblings. Is that related?

Yes, it's the JVM that sometimes messes with attribution of compiled code to the original bytecode.
If you have a test case that reliably reproduces this weird behavior, please let me know - I'll check if it's possible to workaround this somehow in async-profiler.

**Comment by oehme** [comment] 2021-09-06 20:04
I do, but it's a big code base. I'll see if I can force it in a reduced example.

**Comment by oehme** [comment] 2021-09-06 20:57
Here's a very contrived example:

```
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class LineNumberProblem {

    public static void main(String[] args) {

        LongThing seed = new LongThing(1);
        List<Thing> things = Stream.iterate(seed, LineNumberProblem::next).limit(100000).collect(Collectors.toList());

        while (true) {
            Thing previousThing = seed;
            long result = 0;
            for (Thing thing : things) {
                result += Long.compare(previousThing.getAsLong(), thing.getAsLong());
                previousThing = thing;
            }
            System.out.println(result);
        }
    }

    private static Thing next(Thing previous) {
        if (previous instanceof LongThing) {
            return new DoubleThing(1.0);
        } else if (previous instanceof DoubleThing) {
            return new BooleanThing(true);
        } else if (previous instanceof BooleanThing) {
            return new IntThing(2);
        } else {
            return new LongThing(1);
        }
    }

    public interface Thing {
        long getAsLong();
    }

    static class LongThing implements Thing {
        private final long data;

        public LongThing(long data) {
            this.data = data;
        }

        @Override
        public long getAsLong() {
            return data;
        }
    }

    static class IntThing implements Thing {
        private final int data;

        public IntThing(int data) {
            this.data = data;
        }

        @Override
        public long getAsLong() {
            return data;
        }
    }

    static class DoubleThing implements Thing {
        private final double data;

        public DoubleThing(double data) {
            this.data = data;
        }

        @Override
        public long getAsLong() {
            return (long) data;
        }
    }

    static class BooleanThing implements Thing {
        private final boolean data;

        public BooleanThing(boolean data) {
            this.data = data;
        }

        @Override
        public long getAsLong() {
            return data ? 1 : 0;
        }
    }

}

``` 

The flame graph shows `getAsLong` inside `Long.compare`.
![linenumber-problem](https://user-images.githubusercontent.com/1191797/132259848-a9683d71-e702-4d06-b656-1dbe72d15a78.png)

**Comment by apangin** [comment] 2021-09-06 21:36
@oehme Thank you for the test case. Please open a new issue - I'll take a look.
