### ISSUE TITLE
"Could not start attach mechanism: Value too large for defined data type"

### ISSUE THREAD

**Issue by vanaeken** [jvm-profiling-tools/async-profiler#677] opened 2022-11-10 00:26 UTC
We have been using async-profiler with great success for the last couple of years, but we're now running into trouble on specific hosts. We are getting the error message below, both with an older version that we are using, and the recent 2.8.3 version.

```
# ./async-profiler-2.8.3/profiler.sh -e itimer --all-user -d 1 -s -f out.html 13645
Could not start attach mechanism: Value too large for defined data type
```

Note that our JVMs are 32-bit, although the operating system is 64-bit CentOS (I build async-profiler on a 32-bit CentOS system so that we can use it with our 32-bit JVMs).

The OS is CentOS Linux release 7.9.2009 (Core), on the system where we are seeing success, and on the system where we are seeing the error. The hardware is different though (see below).

Do you have any idea what is causing this problem, and how we can resolve it? Thank you.

**HARDWARE where we are seeing success**
```
# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    2
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz
Stepping:              4
CPU MHz:               2599.877
CPU max MHz:           3200.0000
CPU min MHz:           1000.0000
BogoMIPS:              4400.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              19712K
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities
```

**HARDWARE where we are seeing failure**
```
# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    32
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 49
Model name:            AMD EPYC 7452 32-Core Processor
Stepping:              0
CPU MHz:               2345.584
BogoMIPS:              4691.16
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              16384K
NUMA node0 CPU(s):     0-63
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 hw_pstate sme retpoline_amd ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip overflow_recov succor smca
```

**Comment by apangin** [comment] 2022-11-11 18:42
Try `strace` to troubleshoot the problem.
Please show the output of `strace build/jattach 13645 load`
(where 13645 is pid of the Java process which the profiler fails to attach to).

**Comment by apangin** [comment] 2022-11-11 18:45
Try also running 64-bit `jattach` with 32-bit `libasyncProfiler.so`

**Comment by vanaeken** [comment] 2022-11-12 00:04
Andrei, thank you so much for looking into this. I have attached the `strace` output (see below)

Using 64-bit `jattach` with 32-bit `libasyncProfiler.so` **does work**, which actually unblocks us. Do you expect this to work on all our 64-bit CentOS installations, independently of the hardware?

[aync-profiler.strace.txt](https://github.com/jvm-profiling-tools/async-profiler/files/9993695/aync-profiler.strace.txt)

**Comment by apangin** [comment] 2022-11-12 07:05
Yes, if you are running profiler on a 64-bit OS, 64-bit jattach should work regardless of the bitness of the target JVM.
At the same time, bitness of `libasyncProfiler.so` should match the bitness of the JVM.

Not sure why 32-bit jattach does not work in your case - I doubt it's because of the hardware; more likely, there is something wrong with glibc or a way how you compile jattach. From strace output, I see that `stat64` syscall returns success, while the corresponding `stat` call from glibc fails. So it's either a bug in glibc, or you link jattach against a wrong version of libc.

**Comment by vanaeken** [comment] 2022-11-14 17:37
The glibc version is the same on both the problematic and the non-problematic host (see below), and the async-profiler build is the same too (we actually build an async-profiler RPM and distribute that over our hosts). So, yeah, this is a bit of a mystery to me. It's great that we have a workaround though.

```
[bad host]$ ldd --version
ldd (GNU libc) 2.17
[good host]$ ldd --version
ldd (GNU libc) 2.17
```

**Comment by apangin** [comment] 2022-11-17 21:36
From the documentation of [`stat`](https://man7.org/linux/man-pages/man2/stat.2.html) syscall:
```
ERRORS
...
       EOVERFLOW
              pathname or fd refers to a file whose size, inode number,
              or number of blocks cannot be represented in,
              respectively, the types off_t, ino_t, or blkcnt_t.  This
              error can occur when, for example, an application compiled
              on a 32-bit platform without -D_FILE_OFFSET_BITS=64 calls
              stat() on a file whose size exceeds (1<<31)-1 bytes.
```

Seems like exactly your case. I guess, `inode` number of the file fits 32 bit value on one machine, but not on another.

The solution is to use 64-bit jattach.
Since the problem is understood and solution found, I'm closing the issue.

**Closed by apangin** 2022-11-17 21:36 UTC

**Comment by vanaeken** [comment] 2022-11-17 22:04
Andrei, thanks again for your assistance with this issue.

**Comment by leelamv** [comment] 2023-01-05 22:09
Hi @apangin , 

Can we also add "-D_FILE_OFFSET_BITS=64"  for building jattach (having this flag shouldn't hurt 64 bits build and works)
