### ISSUE TITLE
JVM goes unresponsive

### ISSUE THREAD

**Issue by abhaymitra** [jvm-profiling-tools/async-profiler#258] opened 2019-10-17 00:11 UTC
I'm running async-profiler in a loop like so
```
while true; do sudo ./profiler.sh -d 600 `sudo jps | grep <ProcName> | awk '{ print $1 }'` -f flm-`date "+%F-%T"`.svg -b 5000000 && echo "Done profiling at `date "+%F-%T"`"; done
```

After running successfully for around 8 hours, the JVM just got "stuck" for around 10 minutes after which a watchdog process restarted it. It stopped logging (it's a very verbose service) and stopped responding to RPCs.

I had noticed this once before during a manual run as well on the same service.

java info:
```
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by apangin** [comment] 2019-10-17 01:11
Why do you think the problem is related to async-profiler?
What do you mean by "got stuck"? When the process is "stuck", does it consume CPU or is it totally idle? Does the process respond to signals (e.g. `kill -3 PID`)?
When the process hangs next time, try to diagnose it with `strace` or `gdb`.

**Comment by apangin** [comment] 2019-11-23 15:43
Closing the issue, as there is not enough details here, and there has been no feedback from the submitter.
Feel free to reopen when you have more information.

**Closed by apangin** 2019-11-23 15:43 UTC
Labels: need more details
