### ISSUE TITLE
long attach time

### ISSUE THREAD

**Issue by egwepas** [jvm-profiling-tools/async-profiler#328] opened 2020-06-05 22:54 UTC
When attaching to the JVM the profiler waits for 200 seconds before returning.

Then everything works. It seems to be a bit random when i start the profiler on the CLI. But i'm currently auto-starting it via a process created through the profiled app itself, so, i start it at the same poitn every time (after full spring boot startup) and every time i have to wait for (almost exactly) 200s for the process to return.

I have no error message and afterwards it works perfectly

Looks like some king of timeout, any idea ?

**Comment by apangin** [comment] 2020-06-06 00:52
Can you please be a bit more specific?
How do you run the profiler exactly?
Is there the same 200 seconds delay when you run `profiler.sh` from the command line?
Try to load the profiler using JVM `-agentpath` option. You can load the agent library at JVM boot time, but start the profiler any time later.
Are there many classes in your application?
Do you observe a similar effect on other applications?

BTW, if you want to run the profiler from within the application, the preferred way to do so is using profiler's [Java API](https://pangin.pro/async-profiler/api/):
```
AsyncProfiler.getInstance().start(Events.CPU, 1_000_000);
```

**Comment by egwepas** [comment] 2020-06-06 09:53
The details :
* I run using the command : `bash -c '(cd /home/myuser/async-profiler-1.7.1-linux-x64; ./profiler.sh start -b 5000000 -e wall -t -o collapsed -f myoutput --cstack no -t 12345)'`
* I observed the same delay from command line sometimes, but not everytime, it looks like it depends at which moment I attach the profiler, the 200s durations value seemed suspicious to me.
* Indeed that would be better, i thought that the profiler would be started at the same time as the JVM, I will do it that way.
* Yes there is a sh*tload of classes (tens of thousands); it is a huge project ;-)
* I did not try it on another application

Java API would be way simpler indeed. Is it available as a public maven artifact or would we have to register it manually within our maven repo ?

----

Anyway, thanks for that tool, it is helping us quite a lot; both wall and alloc profiling. Also, I was stubborn and made the tool i was speaking of ;-) It's not complete yet but I'm using it. https://github.com/egwepas/apcfv

**Comment by apangin** [comment] 2020-06-06 12:19
Thanks for the details. I suppose the large number of classes is the clue. I've seen a similar problem before.

Actually, it's not the problem of the profiler, but rather a JVM bug [JDK-8062116](https://bugs.openjdk.java.net/browse/JDK-8062116).

When you attach profiler for the first time, it needs to create `jmethodID`s for all methods of all loaded classes (in order to support asynchronous stack traces). Due to the above bug, this can take very long, if there are many loaded classes. Unfortunately, the bug has been fixed only in JDK 9+.

I have a [one line fix](https://github.com/jvm-profiling-tools/async-profiler/issues/14#issuecomment-384935007) that improves the situation in JDK 8, but it requires recompiling JDK.

When you attach profiler at startup as `-javaagent`, it will create `jmethodID`s gradually as the classes are loaded. In this case, there will be no delay when profiler starts, but the overall application startup time will suffer.

**Comment by egwepas** [comment] 2020-06-06 17:05
OK i understand; So, probably, attach it faster before spring boot scans for all the beans, and slower afterwards.

We cannot affor recompiling the JDK, so I'll take the longer startup time.

Concerning the Java API. Should I add the jar bundled with the dist I'm using to the classpath ? Can I add that jar to my maven repo, or is each dist's jar platform-specific (I never practiced JNI) ? Worst case I cas specify a dependency with system scope in my pom...

**Comment by apangin** [comment] 2020-06-06 18:33
Yes, adding `async-profiler.jar` to the classpath should be fine. It is not platform-specific, only Java API.

For it to work, `libasyncProfiler.so` needs to be in the OS standard library path (e.g. `/usr/lib/x86_64-linux-gnu`) or in the directory specified by `-Djava.library.path`

I think I'll make public maven artifact some time soon.

**Comment by egwepas** [comment] 2020-06-06 19:44
Can the java API also attach the agent or do i reference the lib as both agent and lib ?

**Comment by apangin** [comment] 2020-06-06 21:46
Either way will do.
`AsyncProfiler.getInstance` will load profiler library if it hasn't been loaded earlier.

**Comment by egwepas** [comment] 2020-06-11 15:37
I successfully integrated the .so and jar into my project, it's cleaner than calling scripts :-)

I have a question : at some point I was able to explicitely see the GC within call tree, time but I cannot see it anymore. I don't know what changed...

My current settings are : start,framebuf=5000000,event=wall,threads,cstack=no

Is there a setting that could make the GC time appear or disappear from the profiling results ?

**Comment by apangin** [comment] 2020-06-11 16:01
You added `cstack=no` which entirely disables native stacks, including GC threads.

**Comment by egwepas** [comment] 2020-06-12 15:19
Looks like it isn't solving the issue.

At some point I could see a [GC_active] method even with cstack=no, and I was very happy with it. I still cannot find out why i cannot see it anymore ;-)

![image](https://user-images.githubusercontent.com/34545238/84518236-b058b500-acd0-11ea-8c9e-66a838800c3c.png)

**Comment by apangin** [comment] 2020-06-12 22:07
You probably misinterpreted `[GC_active]` frame.

This is actually an *error condition*, which means the profiler wasn't able to recover Java stack trace while a thread was blocked at the global GC-related safepoint. Typically you can see this error when JDK is missing debug symbols, or when running JVM other than HotSpot. I guess you observed `[GC_active]` before installing JDK debuginfo package.

You can return previous behavior with `safemode=16` option (this is an undocumented option to turn off certain profiler features - in this case, Java stack recovery during GC). But I wouldn't recommend doing so.

`[GC_active]` *does not mean anything useful* for performance analysis. It is *not* the amount of time spent in Garbage Collection.

Here is an example of the same code profiled differently:

1) without debug symbols and cstack=no

![gc1](https://user-images.githubusercontent.com/1749416/84549073-c9348b00-ad0f-11ea-95f0-4f6df5b313a9.png)

2) with debug symbols and with native stack traces

![gc2](https://user-images.githubusercontent.com/1749416/84549136-e9fce080-ad0f-11ea-89aa-9dc68f946298.png)

From the first picture, one may think that a thread spends 50% time in GC and 50% time doing useful work in Java. Note, that the `[GC_active]` does not have any Java stack behind it.

However, in reality this code runs `produceGarbage()` in an infinite loop. 80% time a thread is blocked waiting for GC to complete. This can be clearly seen on the second picture. Moreover, you can even distinguish GC caused by an allocation in this thread from GC initiated by other threads.

I realize that reading low-level profiles can be challenging, but they are much more accurate and provide a lot more details. This is actually the main goal (and a unique feature) of async-profiler - to collect such low-level profiles.

**Comment by apangin** [comment] 2020-06-12 22:27
BTW, I think I came up with a workaround that will reduce attach time. Working on it now...

**Comment by egwepas** [comment] 2020-06-12 22:41
Thanks for the detailled explanations. You are right : I misinterpreted [GC_active] for the time spend in GC. This made me want to do an event=alloc profiling, so I installed the debub symbols. And it matched the moment that [GC_active] disapeared.

Intuitively I'd like to be able to know the time globally spent in GC during the profiling (and not counting it in the profiler results) , in order to know if it is worthwhile to switch to alloc profiling in order to reduce the quantity of created objects to reduce the GC workload.

My understanding is that the time spend in GC in method A, could as well be caused by objects created in method B.

Do you think my "methodology" or understanding is wrong or too simple ?

(Thanks for your work for the attach time)

**Comment by egwepas** [comment] 2020-06-13 08:39
Do you think there is a reliable way to estimate time spent in GC ?

Maybe a specific pattern of stack ending with p_thread_cond_wait...

**Comment by apangin** [comment] 2020-06-13 23:04
> Intuitively I'd like to be able to know the time globally spent in GC during the profiling (and not counting it in the profiler results) , in order to know if it is worthwhile to switch to alloc profiling in order to reduce the quantity of created objects to reduce the GC workload.

For this purpose, regular CPU profiling works, as it shows % CPU time spent doing GC, not interfering with the rest of the profile.

**Comment by apangin** [comment] 2020-06-13 23:28
I pushed the workaround for long attach time to [jmethodid](https://github.com/jvm-profiling-tools/async-profiler/tree/jmethodid) branch.

Here is a build with the fix. Give it a try.
[async-profiler-1.7.1s-linux-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/files/4775655/async-profiler-1.7.1s-linux-x64.tar.gz)

**Comment by egwepas** [comment] 2020-06-14 11:33
At first sight it looks like it went (in my case) down from 4m30s to 0.2s ...

Good job !

**Comment by apangin** [comment] 2020-06-14 21:41
Great, thanks for confirming.

**Closed by apangin** 2020-06-14 21:41 UTC
