### ISSUE TITLE
Unexpected EOF reading response while profiling a java application inside Kubernetes pod.

### ISSUE THREAD

**Issue by helario20** [jvm-profiling-tools/async-profiler#621] opened 2022-07-21 23:33 UTC
Async profiler release version: async-profiler-2.8.3-linux-x64
We have a java application running inside a Kubernetes environment.
flavor of JDK: zing-jdk1.8.0-20.03.1.0
While we try to profile we get an **Unexpected EOF reading response** and Kubernetes pods is getting restarted.

After setting set -x flag I get below output.

 linux-x64]# ./profiler.sh start -e cpu,alloc,lock -f profile.jfr <PID>
+ set -eu
+ SCRIPT_BIN=./profiler.sh
+ '[' -h ./profiler.sh ']'
+++ dirname ./profiler.sh
++ cd .
++ pwd -P
+ SCRIPT_DIR=/linux-x64
+ JATTACH=/linux-x64/build/jattach
+ FDTRANSFER=/linux-x64/build/fdtransfer
+ USE_FDTRANSFER=false
+ PROFILER=/linux-x64/build/libasyncProfiler.so
+ ACTION=collect
+ DURATION=60
+ FILE=
+ USE_TMP=true
+ OUTPUT=
+ FORMAT=
+ PARAMS=
+ PID=
+ '[' 6 -gt 0 ']'
+ case $1 in
+ ACTION=start
+ shift
+ '[' 5 -gt 0 ']'
+ case $1 in
+ PARAMS=,event=cpu,alloc,lock
+ shift
+ shift
+ '[' 3 -gt 0 ']'
+ case $1 in
+ FILE=profile.jfr
+ USE_TMP=false
+ shift
+ shift
+ '[' 1 -gt 0 ']'
+ case $1 in
+ PID=<PID>
+ shift
+ '[' 0 -gt 0 ']'
+ '[' <PID> = '' ']'
+ '[' false = true ']'
+ case "$FILE" in
+ FILE=/linux-x64/profile.jfr
+ LOG=/tmp/async-profiler-log.292.<PID>
++ uname -s
+ UNAME_S=Linux
+ '[' Linux = Linux ']'
+ ROOT_PREFIX=/proc/<PID>/root
+ case $ACTION in
+ fdtransfer
+ '[' false = true ']'
+ jattach start,file=/linux-x64/profile.jfr,,event=cpu,alloc,lock
+ set +e
+ /linux-x64/build/jattach <PID> load /linux-x64/build/libasyncProfiler.so true start,file=/linux-x64/profile.jfr,,event=cpu,alloc,lock,log=/tmp/async-profiler-log.292.<PID>
**_Unexpected EOF reading response_**
+ RET=1
+ '[' 1 -ne 0 ']'
+ '[' 1 -eq 255 ']'
+ mirror_log
+ '[' -f /tmp/async-profiler-log.292.<PID> ']'
+ cat /tmp/async-profiler-log.292.<PID>
+ rm /tmp/async-profiler-log.292.<PID>
+ exit 1
[root@kube-pod linux-x64]# command terminated with exit code 137

@apangin

**Comment by Jongy** [comment] 2022-07-22 12:15
The unexpected EOF is most likely because the JVM process has died unexpectedly during the profiler attach.

Can you please provide the output logs from the restarted Pod? `kubectl logs --previous` would contain JVM exit error message.
Also - I am not sure what the 137 refers to (JVM or `profiler.sh`), this is an indication of SIGKILL which might be due to the Pod exceeding its memory limit.

**Comment by helario20** [comment] 2022-07-22 20:36
Here is the log from the crashed pod which is reporting a SEGMENTATION fault.

Signum: [11] - Exiting due to unhandled SIGSEGV exception.
0: rip=0x00007f638adb8522 @rip=[0xffffffffffffffff] (hotspot_os_backtrace_callback.part.16+34) [gcc frame, calls gcc]
1: rip=0x00007f6389c4c62f @rip=[0x00007f62f6cc31d8] (os_backtrace+31) [gcc frame, calls gcc]
2: rip=0x00007f638adb89dd @rip=[0x00007f62f6cc3248] (jvm_unexpected_exception_handler+157) [gcc frame, calls gcc]
3: rip=0x00007f638adb8a85 @rip=[0x00007f62f6cc32f8] (jvm_unexpected_exception_helper+69) [gcc frame, calls gcc]
4: rip=0x00007f6389c4bf65 @rip=[0x00007f62f6cc3308] (jvm_unexpected_exception_handler_wrapper()+101) [gcc frame, calls gcc]
5: rip=0x00007f633070afbb @rip=[0x00007f62f6cc3328] (ElfParser::parseProgramHeaders(CodeCache*, char const*)+11) [gcc frame, calls gcc]
6: rip=0x00007f633071134e @rip=[0x00007f62f6cc3368] (Symbols::parseLibraries(CodeCacheArray*, bool)+1246) [gcc frame, calls gcc]
7: rip=0x00007f63307114f3 @rip=[0x00007f62f6cc3438] (VM::init(JavaVM_*, bool) [clone .part.706]+291) [gcc frame, calls gcc]
8: rip=0x00007f633071c30d @rip=[0x00007f62f6cc3728] (Agent_OnAttach+541) [gcc frame, calls gcc]
9: rip=0x00007f638b3a0871 @rip=[0x00007f62f6cc3858] (JvmtiExport::load_agent_library(char const*, char const*, char const*, outputStream*)+401) [gcc frame, calls gcc]
10: rip=0x00007f638b4bf04f @rip=[0x00007f62f6cc4d28] (attach_listener_thread_entry(JavaThread*, Thread*)+383) [gcc frame, calls gcc]
11: rip=0x00007f638b4a8aee @rip=[0x00007f62f6cc4de8] (JavaThread::thread_main_inner()+190) [gcc frame, calls gcc]
12: rip=0x00007f638b4a8ccc @rip=[0x00007f62f6cc4e58] (JavaThread::run()+460) [gcc frame, calls gcc]
13: rip=0x00007f6389c4cc63 @rip=[0x00007f62f6cc4ef8] (preRun+35) [gcc frame, calls gcc]
#
# An unexpected error has been detected by Java Runtime Environment:
#
#  Segmentation fault (0xb) at pc=0x7f633070afbb, pid=13, tid=409
#
# Java VM: Zing 64-Bit Tiered VM (1.8.0-zing_20.03.1.0-b2-product-linux-X86_64, mixed mode)
# Problematic frame:
# C  [libasyncProfiler.so+0x25fbb]  ElfParser::parseProgramHeaders(CodeCache*, char const*)+0xb
#
# An error report file with more information is saved as:
# ./logs/errors-20220722081207.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by Jongy** [comment] 2022-07-22 23:36
Probably a bug in ELF parsing and probably related to one of the DSOs in your system that async-profiler doesn't handle well. A `/proc/pid/maps` reading might be helpful to filter our possible culpritss (if the bug is not obvious from the code)

**Comment by apangin** [comment] 2022-07-23 23:50
Right, there might be some executable object, which is not a valid ELF file, mapped into the process memory.

Can you show the contents of the crash log `errors-20220722081207.log` or, specifically, the memory map (dynamic libraries section)?

**Comment by helario20** [comment] 2022-07-28 16:36
@Jongy @apangin I am adding the small excerpt from the crashed log:
[errors-20220722081207.log](https://github.com/jvm-profiling-tools/async-profiler/files/9212622/errors-20220722081207.log)

**Comment by apangin** [comment] 2022-08-01 20:34
Unfortunately, this excerpt does not include a memory map I asked about.
Can you please provide the whole log? You may obfuscate the sensitive data and send the log privately to < upload at pangin . pro >

**Comment by apangin** [comment] 2022-08-18 01:29
@linux40 Thank you for the crash log. The problem seems to be specific to the particular kernel version: `Linux 5.19.0-rc3 #1 SMP Mon Jun 27 15:18:33 UTC 2022 aarch64` - something is wrong with the format of `/proc/kallsyms`.
Can you please show the contents of that file? (if you wish, you can send it privately to the email address mentioned above).

I already committed the kallsyms-related fix, but this is a blind change - I'm not sure about the exact cause without seeing the actual file (I installed kernel 5.19, but could not reproduce the issue).

**Comment by apangin** [comment] 2022-08-22 18:17
@linux40 Thank you for providing the file.
Indeed, it seems like a kernel bug. There are some invalid lines with a null byte instead of a symbol time, e.g.:
```
0000000000000000 t cleanup_module	[vfat]
0000000000000000   $x	[fat]
                 ^
                 null character
```
The workaround for this bug is already committed into `master`.

**Comment by apangin** [comment] 2022-09-16 16:53
I committed the fix for the crash in `ElfParser::parseProgramHeaders`

**Closed by apangin** 2022-09-16 16:53 UTC
