### ISSUE TITLE
SIGSEGV on v2.7 JDK8 running on GKE

### ISSUE THREAD

**Issue by imply-cheddar** [jvm-profiling-tools/async-profiler#579] opened 2022-04-07 09:16 UTC
```
# JRE version: OpenJDK Runtime Environment (Zulu 8.60.0.21-CA-linux64) (8.0_322-b06) (build 1.8.0_322-b06)
# Java VM: OpenJDK 64-Bit Server VM (25.322-b06 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libasyncProfiler-linux-x64-a38d71b1e75a7f3c6677da15114e73312b6a9e.so+0x1a2cd]  Profiler::dumpCollapsed(std::ostream&, Arguments&)+0x4bd
```

```
Stack: [0x00007f372647c000,0x00007f372657d000],  sp=0x00007f372657ab30,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libasyncProfiler-linux-x64-a38d71b1e75a7f3c6677da15114e73312b6a9e.so+0x1a2cd]  Profiler::dumpCollapsed(std::ostream&, Arguments&)+0x4bd
C  [libasyncProfiler-linux-x64-a38d71b1e75a7f3c6677da15114e73312b6a9e.so+0x32a3e]  Profiler::dump(std::ostream&, Arguments&)+0xee
C  [libasyncProfiler-linux-x64-a38d71b1e75a7f3c6677da15114e73312b6a9e.so+0x345d6]  Profiler::runInternal(Arguments&, std::ostream&)+0x766
C  [libasyncProfiler-linux-x64-a38d71b1e75a7f3c6677da15114e73312b6a9e.so+0x34cbf]  Java_one_profiler_AsyncProfiler_execute0+0x2df
J 11270  io.pyroscope.one.profiler.AsyncProfiler.execute0(Ljava/lang/String;)Ljava/lang/String; (0 bytes) @ 0x00007f372dcb2c3c [0x00007f372dcb2b80+0xbc]
J 11966 C1 io.pyroscope.one.profiler.AsyncProfiler.dumpCollapsed(Lio/pyroscope/one/profiler/Counter;)Ljava/lang/String; (40 bytes) @ 0x00007f372e882f1c [0x00007f372e882760+0x7bc]
J 12550 C1 io.pyroscope.javaagent.Profiler.dump()Lio/pyroscope/javaagent/Snapshot; (71 bytes) @ 0x00007f372ee50bbc [0x00007f372ee50620+0x59c]
J 11963 C1 io.pyroscope.javaagent.PyroscopeAgent$$Lambda$4.run()V (8 bytes) @ 0x00007f372e251084 [0x00007f372e250f40+0x144]
J 20425 C2 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run()V (59 bytes) @ 0x00007f372fe593c4 [0x00007f372fe59020+0x3a4]
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.so+0x6a6e26]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xea6
V  [libjvm.so+0x6a43c3]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x263
V  [libjvm.so+0x6a49c7]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x57
V  [libjvm.so+0x74611c]  thread_entry(JavaThread*, Thread*)+0x6c
V  [libjvm.so+0xae6bb3]  JavaThread::thread_main_inner()+0x1f3
V  [libjvm.so+0xae6f4d]  JavaThread::run()+0x36d
V  [libjvm.so+0x96f812]  java_start(Thread*)+0x102
C  [libpthread.so.0+0x76db]  start_thread+0xdb
```

Run with `start,threads,event=itimer,interval=10ms`

The call to dumpCollapsed is being passed `Counter.SAMPLES` and the `one.profiler` package things are prefixed with `io.pyroscope` because they are being shaded.

**Comment by apangin** [comment] 2022-04-08 00:45
Do you have a complete `hs_err.log`?
If you wish, you may hide any sensitive data from there, and email the log privately to < upload at pangin . pro >

**Comment by imply-cheddar** [comment] 2022-04-08 05:51
Are there specific sections that you absolutely do care about and that you absolutely don't care about?  I'd like to hide stuff by just removing it if at all possible, but I'm unsure which sections are useful or not.  Like, you don't need all of the open fds, correct?

**Comment by apangin** [comment] 2022-04-10 12:51
All sections have some value (they are purposely printed in the crash log). In this particular case I'm mostly interested in
- Regiters
- Top of stack
- Memory map (dynamic libraries)
- System information (CPU type, OS version, meminfo)

The crash seems to happen when dereferencing `trace->num_frames` in `Profiler::excludeTrace`, but to find out the reason, the execution context would be helpful.
Thanks.

**Comment by apangin** [comment] 2022-04-10 14:58
Never mind, I was able to reproduce the bug myself by stress testing pyroscope with a very small profiling interval and dumping profiles every second.

Pyroscope apparently first dumps the profile and then stops the profiler, while this is usually done in the reverse order. Seems like there is a race when dumping concurrently with the running profiler. I'll investigate this. Meanwhile, as a workaround, you may try to stop profiler before dumping.

**Comment by apangin** [comment] 2022-04-10 23:00
The fix has been pushed.

**Comment by imply-cheddar** [comment] 2022-04-10 23:11
Unfortunately, the code that we are running has been edited a bit from what is available on pyroscopes github.  The code that was running when this happened is using the profiler like: 

```
        instance.stop();
        final Snapshot result = new Snapshot(profilingStarted, Instant.now(), instance.dumpCollapsed(Counter.SAMPLES));

        profilingStarted = Instant.now();
        instance.execute(command);
```

Which should be stopping first.  This change was made when moving up to use 2.7 as I noticed in your continuous profiling mode you were stopping, dumping and starting.  Will send a redacted dump file.

**Comment by apangin** [comment] 2022-04-11 20:28
@imply-cheddar Thank you for the update and the dump file. This is essentially the same crash I've just fixed.
It turns out that swapping `stop` and `dump` reduces the chance of the issue, but does not avoid it completely.

The fix has been committed.
The latest binary is available at https://profiler.tools/builds/async-profiler-2.7-race-linux-x64.tar.gz

**Comment by imply-cheddar** [comment] 2022-04-12 11:59
Any chance you could cut it as `2.7.1` or `2.8` or something where you have it as part of a release?

**Comment by apangin** [comment] 2022-04-27 23:03
async-profiler 2.8-ea has been released; closing the issue.

**Closed by apangin** 2022-04-27 23:03 UTC
Labels: bug

**Comment by imply-cheddar** [comment] 2022-04-28 11:42
Thank you!  Will grab that.

**Comment by imply-cheddar** [comment] 2022-04-28 11:46
Hrm, actually, I just went to grab it and it looks like only the x86 build is included.  Any chance the other architectures could also be included?

**Comment by apangin** [comment] 2022-04-28 23:24
Yes, that's actually an "early access" version for evaluation. The builds for other architectures will follow shortly.
