### ISSUE TITLE
Inlined methods

### ISSUE THREAD

**Issue by kolybelkin** [jvm-profiling-tools/async-profiler#139] opened 2018-07-01 20:08 UTC
How to see inlined methods on flame graph? 

I've found the corresponding code in flameGraph.cpp but can't see them on the graphs.

`} else if (StringUtils::endsWith(name, "_[i]", 4)) {
        // Java inlined frame
        name = name.substr(0, name.length() - 4);
        return aqua;`

Is there additional option for turning them on?

**Comment by apangin** [comment] 2018-07-01 20:14
This is not yet implemented, but there are plans to.
Closing as duplicate of #129

**Closed by apangin** 2018-07-01 20:14 UTC
