### ISSUE TITLE
JVM crash in VM::RetransformClassesHook

### ISSUE THREAD

**Issue by ZyablitskiyA** [jvm-profiling-tools/async-profiler#440] opened 2021-06-09 12:08 UTC
Hi Async-profiler developers!
We see the following crash in our internal testing. The issue is not critical for us.
I can't provide a reproducer.
async-profiler version: 2.0
Please ask if you need some additional info.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fcffcbf23d0, pid=476, tid=478
#
# JRE version: OpenJDK Runtime Environment Zulu11.47+17-NV (11.0.10+1) (build 11.0.10.0.101+1-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu11.47+17-NV (11.0.10.0.101+1-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libasyncProfiler.so+0x313d0]  VM::RetransformClassesHook(_jvmtiEnv*, int, _jclass* const*)+0x60
#
# Core dump will be written. Default location: /export/workspace/ext/out/runtime/core.476
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00007fcff8035800):  JavaThread "main" [_thread_in_native, id=478, stack(0x00007fcfffc72000,0x00007fcfffd73000)]

Stack: [0x00007fcfffc72000,0x00007fcfffd73000],  sp=0x00007fcfffd71880,  free space=1022k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libasyncProfiler.so+0x313d0]  VM::RetransformClassesHook(_jvmtiEnv*, int, _jclass* const*)+0x60
C  [libjckjvmti.so+0x5f27d]  Java_javasoft_sqe_tests_vm_jvmti_rtrc001_rtrc00117_rtrc00117_doTest+0x8b
j  javasoft.sqe.tests.vm.jvmti.rtrc001.rtrc00117.rtrc00117.doTest()I+0
j  javasoft.sqe.tests.vm.jvmti.rtrc001.rtrc00117.rtrc00117.run([Ljava/lang/String;Ljava/io/PrintStream;)I+85
j  javasoft.sqe.tests.vm.jvmti.rtrc001.rtrc00117.rtrc00117.main([Ljava/lang/String;)V+8
v  ~StubRoutines::call_stub
V  [libjvm.so+0x8d1a12]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x3c2
V  [libjvm.so+0x9438c7]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*) [clone .isra.89]+0x227
V  [libjvm.so+0x948121]  jni_CallStaticVoidMethod+0x171
C  [libjli.so+0x526f]  JavaMain+0xa8f

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  javasoft.sqe.tests.vm.jvmti.rtrc001.rtrc00117.rtrc00117.doTest()I+0
j  javasoft.sqe.tests.vm.jvmti.rtrc001.rtrc00117.rtrc00117.run([Ljava/lang/String;Ljava/io/PrintStream;)I+85
j  javasoft.sqe.tests.vm.jvmti.rtrc001.rtrc00117.rtrc00117.main([Ljava/lang/String;)V+8
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000000

Register to memory mapping:

RAX=0x0 is NULL
RBX=0x0 is NULL
RCX=0x00007fcff802a0d0 points into unknown readable memory: 0xfffffffffffffffe | fe ff ff ff ff ff ff ff
RDX=0x0 is NULL
RSP=0x00007fcfffd71880 is pointing into the stack for thread: 0x00007fcff8035800
RBP=0x00007fcfffd718c0 is pointing into the stack for thread: 0x00007fcff8035800
RSI=0x00005653e17a7880 points into unknown readable memory: 0x0000000000000002 | 02 00 00 00 00 00 00 00
RDI=0x00000000fff80006 is an unallocated location in the heap
R8 =0x00005653e17a7880 points into unknown readable memory: 0x0000000000000002 | 02 00 00 00 00 00 00 00
R9 =0x0000000000000008 is an unknown value
R10=0x00007fcfdfe086e1 is at code_begin+897 in an Interpreter codelet
method entry point (kind = native)  [0x00007fcfdfe08360, 0x00007fcfdfe08ce0]  2432 bytes
R11=0x0000000101ce2408 is an oop: java.lang.Class
{0x0000000101ce2408} - klass: 'java/lang/Class'
R12=0x0 is NULL
R13=0x0000000000000001 is an unknown value
R14=0x00007fcf3c002060 points into unknown readable memory: 0x00007fcffeeb8200 | 00 82 eb fe cf 7f 00 00
R15=0x00007fcff8035b48 points into unknown readable memory: 0x00007fcffeea8c80 | 80 8c ea fe cf 7f 00 00


Registers:
RAX=0x0000000000000000, RBX=0x0000000000000000, RCX=0x00007fcff802a0d0, RDX=0x0000000000000000
RSP=0x00007fcfffd71880, RBP=0x00007fcfffd718c0, RSI=0x00005653e17a7880, RDI=0x00000000fff80006
R8 =0x00005653e17a7880, R9 =0x0000000000000008, R10=0x00007fcfdfe086e1, R11=0x0000000101ce2408
R12=0x0000000000000000, R13=0x0000000000000001, R14=0x00007fcf3c002060, R15=0x00007fcff8035b48
RIP=0x00007fcffcbf23d0, EFLAGS=0x0000000000010246, CSGSFS=0x002b000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007fcfffd71880)
0x00007fcfffd71880:   00000064ffd718e0 00007fcffe24a3f9
0x00007fcfffd71890:   00007fcff8035b48 00007fcf7fc0d698
0x00007fcfffd718a0:   0000000000000000 00007fcf7fc0d698
0x00007fcfffd718b0:   00007fcfffd71960 00007fcff8035800
```

**Comment by apangin** [comment] 2021-06-09 16:39
OK, the problem is understood. Another agent calls JVM TI RetransformClasses with a NULL argument, but async-profiler is not ready for this.

The issue should never happen in a normal application. This is apparently a crafted example that intentionally makes an invalid JVM TI call (makes sense, since the crash log suggests this was indeed a JVM TI test).

Anyway, async-profiler should handle such situations, too. I've pushed the fix.

**Closed** 2021-06-10 23:30 UTC
Labels: bug

**Comment by ZyablitskiyA** [comment] 2021-06-11 09:04
Thanks, Andrei!
I have verified the fix.
