### ISSUE TITLE
Allocation profiling on Zing JVM does not show classes being allocated

### ISSUE THREAD

**Issue by vyazelenko** [jvm-profiling-tools/async-profiler#424] opened 2021-04-29 16:19 UTC
When profiling applications on Zing the allocation profile does not show which classes are being allocated.

Here is an example using the https://github.com/spring-projects/spring-petclinic project doing allocation profiling (i.e. `./profiler.sh -d 30 -e alloc --total -f ...`) with Zulu (**`OpenJDK 64-Bit Server VM (25.292-b10) for linux-amd64 JRE (Zulu 8.54.0.21-CA-linux64) (1.8.0_292-b10), built on Apr  6 2021 10:48:03 by "zulu_re" with gcc 4.4.7 20120313 (Red Hat 4.4.7-3)`**) and Zing  (**`Zing 64-Bit Tiered VM (1.8.0_282-zing_21.03.0.0-b6-product) for linux-X86_64, built on Mar 30 2021 06:31:15 by buildmaster with gcc-7.4.0`**)  JVMs (see [all profiles](https://github.com/jvm-profiling-tools/async-profiler/files/6400076/alloc-profiles.zip)):
- Zulu with `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints`
![zulu-alloc](https://user-images.githubusercontent.com/696855/116583758-fc2b4180-a916-11eb-848e-8a1bfb7ae199.png)

- Zing with `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints`
![zing-alloc](https://user-images.githubusercontent.com/696855/116583827-09e0c700-a917-11eb-9ceb-2dc1c6d13a9e.png)

- Zing with `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -XX:+PreserveFramePointer`
![zing-fp-alloc](https://user-images.githubusercontent.com/696855/116583870-149b5c00-a917-11eb-8db9-23786b7ec58b.png)

As can be seen from the above neither of the Zing profiles have blue frames in them with the class names. The second Zing profile with `-XX:+PreserveFramePointer` seems to be more accurate.

**Comment by apangin** [comment] 2021-04-29 21:51
async-profiler uses HotSpot VMStructs to find a pointer to the class name during allocation profiling.
Zing does not provide such information.

Adding support for JEP 331 will likely solve the problem, but only for Java 11+.
Another approach is to analyze Java bytecode at the allocation site. However, this requires a fair amount of work, and still misses allocations from native code.

**Comment by vyazelenko** [comment] 2021-05-02 13:47
@apangin Do you have plans to add support for JEP 331 to async-profiler?

**Comment by apangin** [comment] 2021-05-04 13:04
Yes, JEP 331 support is high on my list, targeted to one of the nearest releases.

**Comment by apangin** [comment] 2021-05-04 13:17
Will close this as a duplicate of #169

**Closed by apangin** 2021-05-04 13:17 UTC
Labels: zing
