### ISSUE TITLE
JVM crash on attaching async profile

### ISSUE THREAD

**Issue by MaXal** [jvm-profiling-tools/async-profiler#154] opened 2018-09-12 16:10 UTC
During our test runs with async profiler we got the following JVM failure:

```A fatal error has been detected by the Java Runtime Environment:
Internal Error (jvmtiExport.cpp:1898), pid=20981, tid=0x00007f9500f5c700
guarantee(collector != NULL) failed: attempt to register stub without event collector
JRE version: OpenJDK Runtime Environment (8.0_152-b12) (build 1.8.0_152-release-1293-b12)
Java VM: OpenJDK 64-Bit Server VM (25.152-b12 mixed mode linux-amd64 compressed oops)
```

What kind of additional information may help to investigate the issue?

**Comment by apangin** [comment] 2018-09-12 20:12
Interesting! I suppose this is a JVM bug - probably, a race condition.
Has it happened immediately after the profiler start?
Please tell how this happened and share the whole hserr.log if possible. Replace any sensible data if needed.
Thanks.

**Comment by apangin** [comment] 2018-10-13 14:57
After a deeper investigation I can confirm this is a JVM bug caused by a race condition.

When profiler attaches, it enables JVMTI DynamicCodeGenerated event. This may occur concurrently to a proceess of vtable_stub generation. The problem happens when the event was not enabled before starting of vtable_stub generation, but became enabled after.

Unfortunately, async-profiler cannot do anything about this. This must be fixed in HotSpot. I submitted the bug report https://bugs.openjdk.java.net/browse/JDK-8212155 with the detailed analysis and with the proposed patch.

To work around the problem load async-profiler at JVM startup using `-agentpath` option.

**Closed by apangin** 2018-10-13 14:57 UTC

**Comment by zdyj3170101136** [comment] 2023-11-30 02:09
> krzysztofslusarski/连续异步分析器#27

if this problem would only occur when attach libasyncProfile.so in process in first time?

if i do continous profiling like below in many times,  only the first asprof start would possible cause the problem.

or every time asprof start would possible cause the problem?
```
asprof start -d 59s --cstack dwarf pid
asprof stop pid
```

**Comment by zdyj3170101136** [comment] 2023-11-30 02:10
> > krzysztofslusarski/连续异步分析器#27
> 
> 是否只有在第一次附加 libasyncProfile.so 时才会出现此问题？
> 
> 如果我多次进行如下所示的连续分析，则只有第一次 asprof 启动可能会导致问题。
> 
> 或者每次 asprof 启动都可能导致问题？
> 
> ```
> asprof start -d 59s --cstack dwarf pid
> asprof stop pid
> ```

my java prod environment is 1.8, i really need to resolve this problem, could you provide some methods for me to fix this?

**Comment by apangin** [comment] 2023-11-30 21:43
> if i do continous profiling like below in many times, only the first asprof start would possible cause the problem.
> or every time asprof start would possible cause the problem?

Only the first time

> some methods for me to fix this

A workaround is mentioned above: add `-agentpath:libasyncProfiler.so` JVM argument

**Comment by zdyj3170101136** [comment] 2023-12-01 02:47
this needs the process owner to do it?
i want to do a non-instrusive continuous profiling system.

Andrei Pangin ***@***.***> 于2023年12月1日周五 05:43写道：
