### ISSUE TITLE
Allocation Profiling issue with Zing VM

### ISSUE THREAD

**Issue by rami-prilutsky** [jvm-profiling-tools/async-profiler#331] opened 2020-07-02 08:49 UTC
Cannot run async profiler in alloc mode. Verified libjvm.so  is in place but still getting: "No AllocTracer symbols found. Are JDK debug symbols installed?"

zing version:

> /opt/zing/zing-jdk8/bin/java -version
> java version "1.8.0-zing_19.01.0.0"
> Zing Runtime Environment for Java Applications (build 1.8.0-zing_19.01.0.0-b2)
> Zing 64-Bit Tiered VM (build 1.8.0-zing_19.01.0.0-b6-product-azlinuxM-X86_64, mixed mode)

> ls /opt/zing/zing-jdk8/jre/lib/amd64/server/
> boilerplate.ll  libjsig.so  libjvm.so  Xusage.txt

**Comment by apangin** [comment] 2020-07-02 21:30
This version of Zing does not support allocation profiling.
Use 19.08.1.0 or later.

Closing as duplicate of #312

**Closed by apangin** 2020-07-02 21:30 UTC
