### ISSUE TITLE
guarantee(loc != NULL) failed: missing saved register

### ISSUE THREAD

**Issue by oehme** [jvm-profiling-tools/async-profiler#416] opened 2021-04-14 17:20 UTC
I just encountered this JVM-internal error while profiling and suspect that it might be related to the profiler, as I haven't seen this error outside of profiling yet.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (oopMap.cpp:352), pid=7174, tid=7200
#  guarantee(loc != NULL) failed: missing saved register
#
# JRE version: OpenJDK Runtime Environment Corretto-11.0.10.9.1 (11.0.10+9) (build 11.0.10+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (11.0.10+9-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
``` 
I can't share the full dump publicly, but let me know if you need more info or if you think this is unrelated to async-profiler.

**Comment by apangin** [comment] 2021-04-14 20:18
Does not look familiar to me.
Can you mail the entire log (with possibly erased sensitive information) to < upload at pangin.pro >? This is my private address.
Has the crash happened just once?

**Comment by oehme** [comment] 2021-04-14 20:29
Yes, it happened only once and hasn't happened again in the next dozen profiling runs. So it's not a critical issue for me.

**Comment by apangin** [comment] 2022-01-01 19:02
I didn't succeed in reproducing this particular crash, however, I committed a couple of stability improvements that might be related. Feel free to reopen the issue if you encounter the problem again with the most recent async-profiler.

**Closed by apangin** 2022-01-01 19:02 UTC

**Comment by apangin** [comment] 2022-01-22 01:00
I've finally found the root cause of the crash and fixed it.
