### ISSUE TITLE
[feature request] Show Inlined frames

### ISSUE THREAD

**Issue by franz1981** [jvm-profiling-tools/async-profiler#129] opened 2018-06-04 16:21 UTC
Mixed mode flame graphs with perf-java-flames show inlined frames 
using aqua color, making easy identify them.
It is possible to do the same with async-profiler?
AGCT allow to recognize these "virtual" frames?

**Comment by apangin** [comment] 2018-06-05 02:46
AGCT does not support this.
But ultimately async-profiler should work without AGCT support.
Closed as duplicate of #66.

**Closed by apangin** 2018-06-05 02:46 UTC
