### ISSUE TITLE
Speedscope output

### ISSUE THREAD

**Issue by huguesb** [jvm-profiling-tools/async-profiler#367] opened 2020-11-10 09:12 UTC
Large flame graphs generated by profiling Spark applications (~10Mb) tend to lock up SVG viewers, even on powerful machines. [Speedscope](https://github.com/jlfwong/speedscope) can deal with large profiles. It would be nice if async-profiler could be extended to output profiles in speedscope format.

**Comment by apangin** [comment] 2020-11-10 09:50
Duplicate of #368 368

**Closed by apangin** 2020-11-10 09:50 UTC
