### ISSUE TITLE
Fresh segfault

### ISSUE THREAD

**Issue by toktarev** [jvm-profiling-tools/async-profiler#536] opened 2022-01-26 19:50 UTC
```
Stack: [0x00007fb3fb887000,0x00007fb3fb988000],  sp=0x00007fb3fb9857f8,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
j  org.apache.spark.SomeRDD$$anon$1.<init>(Lorg/apache/spark/SomeRDD;Lorg/apache/spark/TaskContext;Lorg/apache/spark/Partition;)V+431
j  org.apache.spark.SomeRDD.compute(Lorg/apache/spark/Partition;Lorg/apache/spark/TaskContext;)Lscala/collection/Iterator;+27
j  org.apache.spark.rdd.RDD.computeOrReadCheckpoint(Lorg/apache/spark/Partition;Lorg/apache/spark/TaskContext;)Lscala/collection/Iterator;+26
j  org.apache.spark.rdd.RDD.iterator(Lorg/apache/spark/Partition;Lorg/apache/spark/TaskContext;)Lscala/collection/Iterator;+42

```

@krzysztofslusarski  gave me advice about wall mode

safemode=64,event=wall,thread,interval=1000000,jfr

caused segfault

**Comment by krzysztofslusarski** [comment] 2022-01-26 19:53
What version of async profiler do you use? Can you send the ```hs err``` file?

**Comment by toktarev** [comment] 2022-01-26 19:55
Profiler: v2.5
OS: 5.4.0-1056-gcp #60~18.04.1-Ubuntu SMP Tue Oct 19 15:05:21 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
JDK: 1.8 (without debug symbols) (java-8-openjdk-amd64)

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

**Comment by toktarev** [comment] 2022-01-26 20:01
[hs_err_pid_13315.log](https://github.com/jvm-profiling-tools/async-profiler/files/7945178/hs_err_pid_13315.log)

**Comment by krzysztofslusarski** [comment] 2022-01-26 20:02
Check 2.6, there were 3 issues on 2.5 that were fixed. I usually use wall mode with default interval. Since 2.6 I also use default safemode.

**Comment by toktarev** [comment] 2022-01-26 20:04
This segfault scares me because it happens somewhere inside the java stack.

**Comment by toktarev** [comment] 2022-01-26 20:05
We don't have native library call in that place.

**Comment by krzysztofslusarski** [comment] 2022-01-26 20:08
@apangin can you look at the ```hs err``` and see if it is already fixed in 2.6?

**Comment by toktarev** [comment] 2022-01-26 20:42
I see this on segfault each application run only if the profiler is enabled with wall option.

**Comment by krzysztofslusarski** [comment] 2022-01-26 20:45
Do you get them also on the newest version? There is 2.6 released.

**Comment by toktarev** [comment] 2022-01-26 20:45
I haven't yet checked 2.6

Need some time to re-deploy.

**Comment by toktarev** [comment] 2022-01-26 20:47
It recalls me discussion from https://github.com/jvm-profiling-tools/async-profiler/issues/513.

I might be wrong of course.

**Comment by apangin** [comment] 2022-01-26 21:43
The crash does not look familiar to me, and there is nothing in hs_err.log that points to the profiler.
However, there were recent async-profiler fixes against JVM crashes, so I suggest to try a newer version anyway.

Here is the built from `v2.x` branch: https://profiler.tools/builds/async-profiler-2.6.1-linux-x64.tar.gz
It has everything from 2.6 release plus one more important reliability fix.

**Comment by toktarev** [comment] 2022-01-26 21:46
```
  0x000055c0a03c2000 JavaThread "Async-profiler Timer" daemon [_thread_in_native, id=13470, stack(0x00007fb3fa986000,0x00007fb3fb186000)]
7fb3fd3ec000-7fb3fd43e000 r-xp 00000000 09:00 13631823                   /hadoop/yarn/local/usercache/XXXX/appcache/application_1641922729766_0419/container_1641922729766_0419_01_000139/tmp/profiler16432264031893561621395685560119.so
7fb3fd43e000-7fb3fd63e000 ---p 00052000 09:00 13631823                   /hadoop/yarn/local/usercache/XXXX/appcache/application_1641922729766_0419/container_1641922729766_0419_01_000139/tmp/profiler16432264031893561621395685560119.so
7fb3fd63e000-7fb3fd640000 rw-p 00052000 09:00 13631823                   /hadoop/yarn/local/usercache/XXXX/appcache/application_1641922729766_0419/container_1641922729766_0419_01_000139/tmp/profiler16432264031893561621395685560119.so

```

Points to the profiler.

**Comment by toktarev** [comment] 2022-01-26 21:47
I will try new version ASAP.

**Comment by toktarev** [comment] 2022-01-26 21:53
I use the profiler in very unusual conditions.

Up to 240 JVM, and I start them using java API (without java agent or profiler.sh).

This is why I catch bugs so frequently.

If a person uses 1 JVM per using a profiler.sh it is considerably harder to catch such rare bugs.

**Comment by toktarev** [comment] 2022-01-26 21:57
I was not able to find something else which would let me to collect and save results to HDFS.

JMC does not fit as well.

Plus looks like other people will start using it as well in the nearest future.

**Comment by toktarev** [comment] 2022-01-27 15:08
![image](https://user-images.githubusercontent.com/4003874/151386125-7fba4ab6-833b-4f41-9d3f-ea08285c43b1.png)

**Comment by toktarev** [comment] 2022-01-27 15:09
I got this flamegraph using converter from jfr

**Comment by toktarev** [comment] 2022-01-27 15:10
looks like too many items

**Comment by toktarev** [comment] 2022-02-02 13:14
new stack

Version 2.6

```
Stack: [0x00007f6c6bafb000,0x00007f6c6bbfc000],  sp=0x00007f6c6bbf8460,  free space=1013k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libzip.so+0x5e70]
C  [libzip.so+0x6b0e]
C  [libzip.so+0x49eb]  Java_java_util_zip_ZipFile_getEntry+0x8b
J 121  java.util.zip.ZipFile.getEntry(J[BZ)J (0 bytes) @ 0x00007f6d2138474e [0x00007f6d21384680+0xce]
J 6613 C2 java.util.zip.ZipFile.getEntry(Ljava/lang/String;)Ljava/util/zip/ZipEntry; (101 bytes) @ 0x00007f6d21b8d920 [0x00007f6d21b8d5c0+0x360]
J 1312 C2 sun.misc.URLClassPath.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; (83 bytes) @ 0x00007f6d216b6ac8 [0x00007f6d216b6920+0x1a8]
J 2485 C2 java.net.URLClassLoader$1.run()Ljava/lang/Class; (81 bytes) @ 0x00007f6d21b28e08 [0x00007f6d21b28940+0x4c8]
J 10589 C2 java.net.URLClassLoader$1.run()Ljava/lang/Object; (5 bytes) @ 0x00007f6d2290f054 [0x00007f6d2290f020+0x34]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x69e1a5]
V  [libjvm.so+0x75a8e2]  JVM_DoPrivileged+0x2b2
J 174  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedExceptionAction;Ljava/security/AccessControlContext;)Ljava/lang/Object; (0 bytes) @ 0x00007f6d2139f215 [0x00007f6d2139f140+0xd5]
J 2426 C2 java.net.URLClassLoader.findClass(Ljava/lang/String;)Ljava/lang/Class; (47 bytes) @ 0x00007f6d21a7e53c [0x00007f6d21a7e4a0+0x9c]
J 6154 C2 java.lang.ClassLoader.loadClass(Ljava/lang/String;Z)Ljava/lang/Class; (122 bytes) @ 0x00007f6d21e7982c [0x00007f6d21e78ea0+0x98c]
J 6080 C2 java.lang.ClassLoader.loadClass(Ljava/lang/String;)Ljava/lang/Class; (7 bytes) @ 0x00007f6d21c8b020 [0x00007f6d21c8afe0+0x40]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x69e1a5]
V  [libjvm.so+0x69b91f]
V  [libjvm.so+0x69bfa3]
V  [libjvm.so+0xaa52b6]
V  [libjvm.so+0xaa5d2e]
V  [libjvm.so+0xaa7d06]
V  [libjvm.so+0x4e3a66]
V  [libjvm.so+0x4e4785]
V  [libjvm.so+0x84b778]
V  [libjvm.so+0x84bbd7]
V  [libjvm.so+0x695b2b]

```

**Comment by apangin** [comment] 2022-02-02 13:45
OpenJDK bugtracker shows 50+ issues related to `Java_java_util_zip_ZipFile_getEntry`:
https://bugs.openjdk.java.net/issues/?jql=text%20~%20%22%5C%22Java_java_util_zip_ZipFile_getEntry%5C%22%22
You'll find the possible reasons and fixes in the above reports (spoiler: nothing to do with the profiler, just do not modify JARs loaded by the JVM).

As to async-profiler,

- please use version 2.6.1;
- in case of problems, post the entire `hs_err.log`.

**Comment by toktarev** [comment] 2022-02-02 13:50
@apangin 

1) I use `so` file from the archive you've provided in the previous message.

2) Of course we can blame LogsRDD, (another kind of our java code) other external libraries,
but we observe segfaults only if the profiler is enabled.

I can send hs_err again you will probably say the same 
`there is nothing in hs_err.log that points to the profiler problem`

**Comment by toktarev** [comment] 2022-02-02 13:58
BTW: we do not use Async Profiler in production (only for dev purposes)
I post it here just for information.

Of course, you can just ignore my messages or close issues.

**Closed** 2022-02-02 14:14 UTC

**Comment by krzysztofslusarski** [comment] 2022-02-02 22:35
@toktarev In case of stability - in my previous work I used Async-profiler 1.8.x in continuous mode. The profiler was always enabled on ```wall``` mode. The results were dump every minute. At the end of the last year we had 40 production JVMs profiled continuously, and even more test instances. I believe in one year of such a profiling we had 1 crash - https://github.com/jvm-profiling-tools/async-profiler/issues/461. My previous company is in the middle of switching to 2.x line.

I'm not as good as @apangin in analyzing ```hs_err``` files, but I cannot see anything related to profiler in a problematic thread. 

I understand what you have written, that there is no error without async-profiler, and there is with async-profiler, but it doesn't mean that async-profiler is guilty here.

One example from my life, there is a Spring component called ```Spring Session JDBC```. It works great, has no problem at all. But if you add ```CAS Client``` to your application then you have a memory leak in ```Spring Session JDBC``` component. This is the same situation, you add ```CAS Client``` and your application has a problem, but it is a fault of ```Spring Session JDBC``` which doesn't emit some events by design.

**Comment by apangin** [comment] 2022-02-02 23:41
Just to clarify why I closed the issue (besides the fact you've told me to).

1. The original problem was reported against 2.5, and I've pointed out that 2.6.1 has important stability updates that will likely help.
2. Your new crash does not have a sign of async-profiler, nor it has anything that may help me in investigating the issue. For some reason (that I can't really understand), you haven't provided the detailed crash report. So it's actually not the "information", but rather an informational noise.
3. The last stack trace exactly matches the stack traces from other crash reports in JDK bug tracker. Those reports are connected with a completely different problem, which I have mentioned and posted a link to.
4. In the lack of further details, that's basically all I can do regarding this issue, as I obviously don't have access to your system and application. That's not my whim, but a general way how open source works. E.g. if you look at OpenJDK crash reports, you'll find that the majority of them that have neither analysis nor a test case, are eventually closed as "Incomplete".

So please do not take offence. I'm here to help, and if you want me to help you with *your* issues, be kind to make an effort from your side as well.

**Comment by toktarev** [comment] 2022-02-03 08:21
@krzysztofslusarski ,

I enabled profiler (2.6.1) on the dev cluster and make some runs:
works, works, works, segfault, works, segfault .. works,...., segfault, works.

I disable profiler (2.6.1) on the dev cluster and make some runs
works, works, works, works, works, works ..... ........works .....................  works.

Of course, maybe this is a problem not with the profiler and I see segfault as a result of a problem with Zip library and 
LogRDD accidentally in exactly that moment when the profiler is enabled.

I call such things - miracles.

**Comment by toktarev** [comment] 2022-02-03 11:04
I see another issue today.

Empty jfr file on some nodes after 3-4 minutes of profiling.

I don't know what kind of evidences I should provide here.
