### ISSUE TITLE
jvm crash problems with newest code(2019-2-26)

### ISSUE THREAD

**Issue by chwu1203** [jvm-profiling-tools/async-profiler#204] opened 2019-02-26 11:42 UTC
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f9dd9f830fc, pid=55258, tid=140313196082944
#
# JRE version: 6.0_33-b04
# Java VM: Java HotSpot(TM) 64-Bit Server VM (20.8-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x43f0fc]  frame::entry_frame_is_first() const+0xc
#
# If you would like to submit a bug report, please visit:
#   http://java.sun.com/webapps/bugreport/crash.jsp


Stack: [0x00007f9d362db000,0x00007f9d3635c000],  sp=0x00007f9d36357650,  free space=497k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x43f0fc]  frame::entry_frame_is_first() const+0xc
V  [libjvm.so+0x439959]  find_initial_Java_frame(JavaThread*, frame*, frame*, methodOopDesc**, int*)+0x4a9
V  [libjvm.so+0x43914e]  forte_fill_call_trace_given_top(JavaThread*, ASGCT_CallTrace*, int, frame)+0x7e
V  [libjvm.so+0x439005]  AsyncGetCallTrace+0x1e5
C  [libasyncProfiler.so+0x188b3]  Profiler::getJavaTraceAsync(void*, ASGCT_CallFrame*, int)+0x83

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
```

**Comment by apangin** [comment] 2019-02-26 13:57
This looks like a JVM bug.
JDK 6u33 is a way too old, I know there were bugs in `AsyncGetCallTrace` API.

Do you have a test case that reproduces the problem?

**Comment by apangin** [comment] 2019-05-20 00:23
I'm closing the issue, since this is a JVM bug, and there are no plans to work around it for a such an old version of JDK.

**Closed by apangin** 2019-05-20 00:23 UTC
