### ISSUE TITLE
Math to calculate the time that the profiled application spent in the runnable state

### ISSUE THREAD

**Issue by wndrws** [jvm-profiling-tools/async-profiler#582] opened 2022-04-27 19:08 UTC
Hello,

Recently I have used async-profiler via IntelliJ IDEA (the agent params were `event=cpu,interval=1ms,jfrsync=profile`) to perform CPU profiling of my application. In addition to that, I performed CPU sampling with the help of Java Visual VM, which showed that a substantial amount of time was spent in I/O bound calls, like waiting for network packets.

As far as I understand, async-profilier in the `-e cpu` mode will collect frames only from threads that are in the runnable state when sampled. For that reason I assumed that I can multiply the profiling interval by the total number of samples collected during profiling and thus I will get the time my application spent on the "actual" work, i.e. the total real time my code spent in the runnable state.

Later I repeated the experiment with the same settings but under higher load (almost 100% CPU usage) and, to my surprise, I got fewer samples in the profile collected by async-profiler given the same profiling duration. I strongly believe that my application spent _more_ time in the runnable state and this doesn't fit the hypothesis that "more samples means more actual work". That made me thinking that actual math must be more complex.

I was looking at other information IntelliJ IDEA and async-profiler collected for me, and eventually I noticed the following log messages:

> 1651007588607575200epochns	DEBUG	Sampling thread statistics for thread 'Java threads sampler': TOTAL_COLLECTED_SAMPLES: 6108; no_running_thread_found_for_sample: 5; change_context_thread_waiting_count: 15124; expected_sleep_duration: 6114000000; actual_sleep_duration: 16523793200; avg one_sample_loop_time: 16534833 (ns); avg get_sample_time: 3511884 (ns); avg record_sample_time: 1088624 (ns)	Type(profiler.Log)
> 
> 1651007588607466400epochns	DEBUG	Sampling thread statistics for thread 'Native threads sampler': TOTAL_COLLECTED_SAMPLES: 191; no_running_thread_found_for_sample: 1238; change_context_thread_waiting_count: 47272; expected_sleep_duration: 1430000000; actual_sleep_duration: 7731179900; avg one_sample_loop_time: 98991709 (ns); avg get_sample_time: 2319293 (ns); avg record_sample_time: 525828 (ns)	Type(profiler.Log)

That's how it looked in IntelliJ IDEA:

![image](https://user-images.githubusercontent.com/17854212/165598439-f2103101-0321-4a37-b112-25f1e61de195.png)

At that moment I understood (I hope, I did it correctly), that the high load on the OS made it harder for async-profiler to perform sampling, and it could not manage to take a sample every 1 ms, and I guessed that the actual sampling interval can be derived from that "sampling thread statistics". I took the `one_sample_loop_time` values for both kinds of frames (Java and Native), multiplied them by the respective samples count and added together. The result that I got almost matched the profiling duration that was 118 seconds:

![image](https://user-images.githubusercontent.com/17854212/165598260-2f4dd3c4-ed63-462a-ba9b-4602cf710e60.png)

So, at that point I assume that in order to calculate the time that the profiled code spent in the runnable state (when using async-profiler in the `-e cpu` mode), I should not use the profiling interval that I specified for async-profiler, but instead I have to check the profiler log messages for sampling thread statistics and do the math based on the reported times and collected samples count. Can you say if it is a correct assumption, please? And if yes, what can be the correct formula? If no, then I will be grateful for some explanation on how to find out the time I interested in.

**Comment by apangin** [comment] 2022-04-27 19:56
Thank you for your interest in async-profiler.
Unfortunately, I'm not in position to comment on IntelliJ IDEA issues here. Please report at https://youtrack.jetbrains.com/ instead.

However, if you can reproduce the problem with the [original release](https://github.com/jvm-profiling-tools/async-profiler/releases) of async-profiler outside IDE, please go ahead and post the update here - I'll definitely take a look.

**Comment by apangin** [comment] 2022-04-27 20:53
Are you on Windows?

**Comment by wndrws** [comment] 2022-04-28 19:24
Yes, the experiments described above were carried out on Windows 10. 
Then, I will try to reproduce them on Ubuntu with the original release of async-profiler outside IDE. It will take some time though. I'll post the results as soon as they are ready.

**Comment by apangin** [comment] 2022-04-28 23:40
OK, I expect this to be a Windows-specific issue. Async-profiler for Windows is a separate project supported by JetBrains.

@KirillTim Do you have anything to suggest?

**Comment by apangin** [comment] 2022-05-25 23:24
Closing the issue, since there is nothing to do on the async-profiler end.

**Closed by apangin** 2022-05-25 23:24 UTC
Labels: question, external
