### ISSUE TITLE
Percentage of sampling traces are low in async-profiler

### ISSUE THREAD

**Issue by sattishv** [jvm-profiling-tools/async-profiler#225] opened 2019-07-03 09:11 UTC
Hi Panjin,

Appreciate your contribution to async-profiler. Its commendable effort. 
Since we are planning to integrate async-profiler as an one stop APM solution for all our apps we have been asked to evaluate async-profiler against JMC. 
During evaluation we noticed few deviations in samples been collected while comparing the performance data between async-profiler against Java Mission Control(JMC). 
Total samples count was huge for async-profiler compared against JMC . We are cleat that its due to asyncgetcalltrace. 
Top methods were highlighted properly.
But samples percentage for few non critical packages was shown less in async-profiler compared against JMC. Since the samples are collected from the same app the samples percentage should be same for all packages right. We would like to know how samples collection been performed in async-profiler. Any inputs or assumptions behind the deviations. Even though we dont see it as an issue we would like to understand. Could you please clarify

We enabled -XX:+DebugNonSafepoints. 
Command executed inside docker:
./profiler.sh -e itimer -s 30 -f /tmp/sample.svg $PID we used itimer since we couldn't inside perf inside the container and due to restricted access to host.
Are we missing something from our side . Please guide us

Sattish.

**Comment by sattishv** [comment] 2019-07-04 07:04
Hi Panjin,
Is it possible to record only Java stacks in async-profiler. We tried with the flag  --all-user but still we could see events related GC and Native code in the dump. Since we want to compare with JFR dump do we have an option in async-profiler to dump only Java stacks. Please confirm

Sattish.

**Comment by apangin** [comment] 2019-07-06 09:18
async-profiler and JMC (or, more precisely, Flight Recorder) work differently.

In `itimer` mode async-profiler wakes up every period of **cpu time** and gets a stack trace from one of the threads currently **scheduled on cpu**.

Flight Recorder wakes up every period of **wall-clock time** and gets stack traces from a subset of **all threads**. So, it's more like async-profiler's `-e wall` mode, except that it skips non-runnable (blocked / waiting / sleeping) threads.

The problem is - JVM does not distinguish idle and busy threads executing a native method. E.g. when there are two threads both executing `SocketInputStream.read`, if one of the threads is actively receiving data, and the other thread is just waiting for incoming data, JVM will not make a difference - from its point of view both threads will be in RUNNABLE state. However, only one of these threads will consume CPU time.

In the above example async-profiler will sample only one thread receiving data, while Flight Recorder will sample both, because JVM thinks both are RUNNABLE. This is my guess where the difference comes from, though I can't be absolutely sure without seeing the profiles or the code.

**Comment by apangin** [comment] 2019-07-06 09:45
> Is it possible to record only Java stacks in async-profiler. We tried with the flag --all-user but still we could see events related GC and Native code in the dump. Since we want to compare with JFR dump do we have an option in async-profiler to dump only Java stacks.

Well, the ability of profiling JVM and native code is one of the main advantages of async-profiler. This part of the profile is the **essential difference** between AP and JFR. Since you are comparing the tools, you want to know what the difference is, right? So why make the output intentionally worse, just to make it look more like JFR?

But it is still possible to get a profile without JVM part: create a dump in a `collapsed` text format, filter out all lines starting with `start_thread` (a simple `grep` command), and then use [FlameGraph](https://github.com/brendangregg/FlameGraph) script to convert text output to SVG.

I plan to add general purpose filtering to async-profiler (#187) to avoid such kind of manipulations with grep etc.

**Comment by sattishv** [comment] 2019-07-08 11:44
Hi ,

Thanks for clarifying our queries. This was really useful to us for comparing the performance data between JFR and async-profoler. Will get back to you incase we need few more details.

Thanks
Sattish.

**Comment by sattishv** [comment] 2019-07-17 11:46
Hi ,

Sorry for continuing with the same topic. Today we executed series tests with different number of concurrent users(5,10,15)  same requests rate on the same code base. When analyzed we found the samples count increased relatively with the number of users. But the package percentage % match for ex. org.apache. reduced with the number of users increased. The percentage match calculated for each packages got reduced with the test having 15 users. For 5 users test percentage was high. We are curious to know how the samples are collected and how the cpu time is calculated from each samples. Could you please clarify

Thanks

**Comment by sattishv** [comment] 2019-07-17 16:55
Hi ,

Sorry i missed your statement which you mentioned before on stack trace collection.
"itimer mode async-profiler wakes up every period of cpu time and gets a stack trace from one of the threads currently scheduled on cpu."
1. How are we calculating the cpu time spent from the static stack trace. 
2. why are we seeing the difference in percentage per package in search option for different user test.

Thanks in advance

**Comment by apangin** [comment] 2019-07-17 23:22
[This article](https://queue.acm.org/detail.cfm?id=2927301) by Brendan Gregg should explain how to interpret Flame Graphs (including those collected by async-profiler).

This is a sampling profiler. It does not tell exactly how much time was spent in a specific method, or how many times the method was executed. Though it may give an estimate as discussed in #107.

It's absolutely possible that some methods have higher or lower percentage of samples depending on the load. This behavior is purely application-specific. So far I don't see a contradiction. If you suspect that data collected by async-profiler is somehow wrong, please open an new issue, attach the suspicious profile and, if possible, provide a test case that demonstrates the problem.

**Comment by sattishv** [comment] 2019-07-18 06:42
Hi,

Thanks once again for clarifying us. 

> It's absolutely possible that some methods have higher or lower percentage of samples depending on the load. This behavior is purely application-specific. So far I don't see a contradiction. 

I agree Yes you are right . But our question is different . To make it clear
Let me list our test parameters
5 user test recorded 30,000 samples
10 user recorded 50,000 samples
15 user recorded 70.000 samples
But the match percentage for few packages e.g (org.springframework) varies with the workload. For 5 user test it was high compared to 15 user test. 
Our question is with the high samples count been recorded in 15 user how come package percentage went low compared to 5 user test where samples count is less. Does the samples resides within other packages. 

If you suspect that data collected by async-profiler is somehow wrong, please open an new issue, attach the suspicious profile and, if possible, provide a test case that demonstrates the problem.

We arent suspecting the data we would like to understand why we see match percentage for certain packages is low as the load increases. Thought understanding the collection behavior of async will help us to understand the behavior.
Let me collect the samples with output format as flat and see what we incur from it.

Thanks

**Comment by sattishv** [comment] 2019-07-18 10:39
Hi ,

while searching we came across this blog where they have cleared explained how sampling technique works and how the metrics like total self time been calculated . Can you let us know are we following this similar approach in collecting samples.

https://devblogs.microsoft.com/devops/how-cpu-sampling-works/

Thanks

**Comment by apangin** [comment] 2019-07-18 11:29
Yes, that's how sampling profilers (including async-profiler) typically work.

**Comment by sattishv** [comment] 2019-07-23 11:34
Thanks. In flat file format we could see data been measured as

          ns  percent  samples  top
  ----------  -------  -------  ---
 13420000000    4.34%     1342  ObjArrayKlass::allocate(int, Thread*)

want to confirm what does ns denotes is it nano seconds or something else. Please confirm

**Comment by apangin** [comment] 2019-07-23 12:28
Yes, that's the *estimated* CPU time in nanoseconds spent in the function.
The key word is *estimated*, because the exact time cannot be known with a sampling profiler.

In this case the estimation is pretty straightforward: if the sampling interval is 10 ms (the default), and the function receives 1342 samples, then the total time is computed as 1342 * 10 ms = 13.42 s.

**Comment by sattishv** [comment] 2019-07-23 16:29
Thanks for the immediate response. Appreciate your commitment

**Closed** 2019-08-25 14:05 UTC
Labels: question
