### ISSUE TITLE
Failed to inject profiler into 74173

### ISSUE THREAD

**Issue by leonchen83** [jvm-profiling-tools/async-profiler#372] opened 2020-11-19 10:01 UTC
linux version
Linux noldor-dev 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

java version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

async-profiler version
async-profiler-1.8.2-linux-x64

exec
```
sudo /usr/local/jdk/bin/jps
74173 PricerStartup

sudo ./profiler.sh -d 30 -e cpu -f pricer.svg 74173
```

error
```
Failed to inject profiler into 74173
        linux-vdso.so.1 (0x00007ffc623b2000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f5358397000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5358177000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f5357f6e000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f5357bd9000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f5357857000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f535763f000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f535727d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5358bdf000)
```

**Comment by apangin** [comment] 2020-11-19 11:04
Duplicate of #203, #78 

Make sure the JVM process has acess to the profiler directory.

**Closed** 2020-11-25 03:36 UTC
